openapi: 3.0.0
info:
  title: badge
  description: OpenAPI schema for managing badges
  version: v1beta1

tags:
  - name: Badge

paths:

  /api/organizations/badges:

    post:
      x-internal: ["cloud"]
      operationId: createOrUpdateBadge
      tags:
        - Badge
      summary: Create a new badge or update an existing badge
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Badge"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Badge"

components:
  schemas:
    Badge:
      type: object
      required:
        - id
        - label
        - name
        - org_id
        - description
        - image_url
        - created_at
        - updated_at
        - deleted_at
      properties:
        id:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/uuid"
          x-go-name: ID
          x-oapi-codegen-extra-tags:
            db: "id"
            json: "id"

        org_id:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/uuid"
          description: The ID of the organization in which this badge is available .
          x-oapi-codegen-extra-tags:
            db: "org_id"
            json: "org_id"

        label:
          type: string
          description: unique identifier for the badge ( auto generated )
          example: Kubernetes-Expert
          x-oapi-codegen-extra-tags:
            db: "label"
            json: "label"

        name:
          type: string
          description: Concise descriptor for the badge or certificate.
          example: Kubernetes Expert
          x-oapi-codegen-extra-tags:
            db: "name"
            json: "name"

        description:
          type: string
          description: A description of the milestone achieved, often including criteria for receiving this recognition.
          example: Awarded for mastering Kubernetes concepts and practices.
          x-oapi-codegen-extra-tags:
            db: "description"
            json: "description"

        image_url:
          type: string
          format: uri
          description: URL to the badge image
          example: https://raw.githubusercontent.com/layer5io/layer5-academy/refs/heads/master/static/11111111-1111-1111-1111-111111111111/images/meshery-logo-light.webp
          x-oapi-codegen-extra-tags:
            db: "image_url"
            json: "image_url"

        created_at:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/created_at"

        updated_at:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/updated_at"

        deleted_at:
          $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/deleted_at"