// Package environment provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1beta1

import (
	"github.com/gofrs/uuid"
	externalRef1 "github.com/meshery/schemas/models/core"
)

// Environment defines model for environment.
type Environment struct {
	ID        externalRef1.GeneralId `db:"id" json:"id"`
	CreatedAt externalRef1.Time      `json:"created_at,omitempty"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt      externalRef1.NullTime       `json:"deleted_at,omitempty"`
	Description    externalRef1.Text           `json:"description,omitempty"`
	Metadata       externalRef1.MapObject      `json:"metadata,omitempty"`
	Name           externalRef1.Text           `json:"name,omitempty"`
	OrganizationId externalRef1.OrganizationId `db:"organization_id" json:"organization_id"`
	Owner          *uuid.UUID                  `db:"owner" json:"owner"`
	UpdatedAt      externalRef1.Time           `json:"updated_at,omitempty"`
}

// EnvironmentConnectionMapping defines model for environmentConnectionMapping.
type EnvironmentConnectionMapping struct {
	ID           externalRef1.GeneralId `db:"id" json:"id"`
	ConnectionId uuid.UUID              `db:"connection_id" json:"connection_id"`
	CreatedAt    externalRef1.Time      `json:"created_at,omitempty"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt     externalRef1.NullTime `json:"deleted_at,omitempty"`
	EnvironmentId uuid.UUID             `db:"environment_id" json:"environment_id"`
	UpdatedAt     externalRef1.Time     `json:"updated_at,omitempty"`
}

// EnvironmentPage defines model for environmentPage.
type EnvironmentPage struct {
	Environments []Environment       `json:"environments,omitempty"`
	Page         externalRef1.Number `json:"page,omitempty"`
	PageSize     externalRef1.Number `json:"page_size,omitempty"`
	TotalCount   externalRef1.Number `json:"total_count,omitempty"`
}

// EnvironmentPayload defines model for environmentPayload.
type EnvironmentPayload struct {
	// OrgId Organization ID
	OrgId       string            `json:"organization_id"`
	Description externalRef1.Text `json:"description,omitempty"`
	Name        externalRef1.Text `json:"name"`
}
