/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sub category of the model determines the secondary grouping.
 */
export type SubCategory =
  | "API Gateway"
  | "API Integration"
  | "Application Definition & Image Build"
  | "Automation & Configuration"
  | "Certified Kubernetes - Distribution"
  | "Chaos Engineering"
  | "Cloud Native Storage"
  | "Cloud Provider"
  | "CNI"
  | "Compute"
  | "Container Registry"
  | "Container Runtime"
  | "Container Security"
  | "Container"
  | "Content Delivery Network"
  | "Continuous Integration & Delivery"
  | "Coordination & Service Discovery"
  | "Database"
  | "Flowchart"
  | "Framework"
  | "Installable Platform"
  | "Key Management"
  | "Key Management Service"
  | "Kubernetes"
  | "Logging"
  | "Machine Learning"
  | "Management Governance"
  | "Metrics"
  | "Monitoring"
  | "Networking Content Delivery"
  | "Operating System"
  | "Query"
  | "Remote Procedure Call"
  | "Scheduling & Orchestration"
  | "Secrets Management"
  | "Security Identity & Compliance"
  | "Service Mesh"
  | "Service Proxy"
  | "Source Version Control"
  | "Storage"
  | "Specifications"
  | "Streaming & Messaging"
  | "Tools"
  | "Tracing"
  | "Uncategorized"
  | "Video Conferencing";

/**
 * Meshery Models serve as a portable unit of packaging to define managed entities, their relationships, and capabilities.
 */
export interface HttpsSchemasMesheryIoModelJson {
  /**
   * Uniquely identifies the entity (i.e. component) as defined in a declaration (i.e. design).
   */
  id: string;
  /**
   * Specifies the version of the schema used for the definition.
   */
  schemaVersion: string;
  /**
   * Version of the model definition.
   */
  version: string;
  /**
   * The unique name for the model within the scope of a registrant.
   */
  name: string;
  /**
   * Human-readable name for the model.
   */
  displayName: string;
  /**
   * Description of the model.
   */
  description: string;
  /**
   * Status of model, including:
   * - duplicate: this component is a duplicate of another. The component that is to be the canonical reference and that is duplicated by other components should not be assigned the 'duplicate' status.
   * - maintenance: model is unavailable for a period of time.
   * - enabled: model is available for use for all users of this Meshery Server.
   * - ignored: model is unavailable for use for all users of this Meshery Server.
   */
  status: "ignored" | "enabled" | "duplicate";
  registrant: HttpsSchemasMesheryIoComponentJson;
  /**
   * ID of the registrant.
   */
  registrantId: string;
  /**
   * ID of the category.
   */
  categoryId: string;
  category: HttpsSchemasMesheryIoCategoryJson;
  subCategory: SubCategory;
  /**
   * Metadata containing additional information associated with the model.
   */
  metadata?: {
    /**
     * Capabilities associated with the model
     */
    capabilities?: HttpsSchemasMesheryIoCapabilityJson[];
    /**
     * Indicates whether the model and its entities should be treated as deployable entities or as logical representations.
     */
    isAnnotation?: boolean;
    /**
     * Primary color associated with the model.
     */
    primaryColor?: string;
    /**
     * Secondary color associated with the model.
     */
    secondaryColor?: string;
    /**
     * SVG representation of the model in white color.
     */
    svgWhite: string;
    /**
     * SVG representation of the model in colored format.
     */
    svgColor: string;
    /**
     * SVG representation of the complete model.
     */
    svgComplete?: string;
    /**
     * The shape of the node's body. Note that each shape fits within the specified width and height, and so you may have to adjust width and height if you desire an equilateral shape (i.e. width !== height for several equilateral shapes)
     */
    shape?:
      | "ellipse"
      | "triangle"
      | "round-triangle"
      | "rectangle"
      | "round-rectangle"
      | "bottom-round-rectangle"
      | "cut-rectangle"
      | "barrel"
      | "rhomboid"
      | "diamond"
      | "round-diamond"
      | "pentagon"
      | "round-pentagon"
      | "hexagon"
      | "round-hexagon"
      | "concave-hexagon"
      | "heptagon"
      | "round-heptagon"
      | "octagon"
      | "round-octagon"
      | "star"
      | "tag"
      | "round-tag"
      | "vee"
      | "polygon";
    [k: string]: unknown;
  };
  model: Model;
  relationships: unknown[];
  components: unknown[];
  /**
   * Number of components associated with the model.
   */
  componentsCount: number;
  /**
   * Number of relationships associated with the model.
   */
  relationshipsCount: number;
  /**
   * Timestamp when the resource was created.
   */
  created_at?: string;
  /**
   * Timestamp when the resource was updated.
   */
  updated_at?: string;
}
/**
 * Meshery Connections are managed and unmanaged resources that either through discovery or manual entry are tracked by Meshery. Learn more at https://docs.meshery.io/concepts/logical/connections
 */
export interface HttpsSchemasMesheryIoComponentJson {
  /**
   * ID
   */
  id: string;
  /**
   * Connection Name
   */
  name: string;
  /**
   * Credential ID
   */
  credential_id?: string;
  /**
   * Connection Type
   */
  type: string;
  /**
   * Connection Subtype
   */
  sub_type: string;
  /**
   * Connection Kind
   */
  kind: string;
  metadata?: {
    [k: string]: unknown;
  };
  /**
   * Connection Status
   */
  status:
    | "discovered"
    | "registered"
    | "connected"
    | "ignored"
    | "maintenance"
    | "disconnected"
    | "deleted"
    | "not found";
  /**
   * A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
   */
  user_id?: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
  environments?: HttpsSchemasMesheryIoEnvironmentJson[];
  /**
   * Specifies the version of the schema used for the definition.
   */
  schemaVersion: string;
}
/**
 * Meshery Environments allow you to logically group related Connections and their associated Credentials.. Learn more at https://docs.meshery.io/concepts/logical/environments
 */
export interface HttpsSchemasMesheryIoEnvironmentJson {
  /**
   * ID
   */
  id: string;
  /**
   * Environment name
   */
  name: string;
  /**
   * Environment description
   */
  description: string;
  /**
   * Environment organization ID
   */
  organization_id: string;
  /**
   * Environment owner
   */
  owner?: string;
  created_at?: string;
  metadata?: {
    [k: string]: unknown;
  };
  updated_at?: string;
  deleted_at?: string;
}
/**
 * Category of the model.
 */
export interface HttpsSchemasMesheryIoCategoryJson {
  /**
   * A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
   */
  id: string;
  /**
   * The category of the model that determines the main grouping.
   */
  name:
    | "Analytics"
    | "App Definition and Development"
    | "Cloud Native Network"
    | "Cloud Native Storage"
    | "Database"
    | "Machine Learning"
    | "Observability and Analysis"
    | "Orchestration & Management"
    | "Platform"
    | "Provisioning"
    | "Runtime"
    | "Security & Compliance"
    | "Serverless"
    | "Tools"
    | "Uncategorized";
  metadata: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Meshery manages entities in accordance with their specific capabilities. This field explicitly identifies those capabilities largely by what actions a given component supports; e.g. metric-scrape, sub-interface, and so on. This field is extensible. Entities may define a broad array of capabilities, which are in-turn dynamically interpretted by Meshery for full lifecycle management.
 */
export interface HttpsSchemasMesheryIoCapabilityJson {
  /**
   * Specifies the version of the schema to which the capability definition conforms.
   */
  schemaVersion: string;
  /**
   * Version of the capability definition.
   */
  version: string;
  /**
   * Name of the capability in human-readible format.
   */
  displayName: string;
  /**
   * A written representation of the purpose and characteristics of the capability.
   */
  description: string;
  /**
   * Top-level categorization of the capability
   */
  kind: ("action" | "mutate" | "view" | "interaction") & string;
  /**
   * Classification of capabilities. Used to group capabilities similar in nature.
   */
  type: string;
  /**
   * Most granular unit of capability classification. The combination of Kind, Type and SubType together uniquely identify a Capability.
   */
  subType: string;
  /**
   * Key that backs the capability.
   */
  key: string;
  /**
   * State of the entity in which the capability is applicable.
   */
  entityState: ("declaration" | "instance")[];
  /**
   * Status of the capability
   */
  status: "enabled" | "disabled";
  /**
   * Metadata contains additional information associated with the capability. Extension point.
   */
  metadata?: {
    [k: string]: unknown;
  };
}
/**
 * Registrant-defined data associated with the model. Properties pertain to the software being managed (e.g. Kubernetes v1.31).
 */
export interface Model {
  /**
   * Version of the model as defined by the registrant.
   */
  version: string;
  [k: string]: unknown;
}
