
components:
  schemas:
    mesheryApplication:
      properties:
        id:
          $ref: ../common.yml#/id
        user_id:
          $ref: ../common.yml#/id
        application_file:
          $ref: ../common.yml#/text
          description: Application file
        name:
          $ref: ../common.yml#/text
          description: Pattern Name
        location:
          $ref: ../common.yml#/map_object
        visibility:
          $ref: ../common.yml#/text
        source_type:
          enum: [k8s_manifest, docker_compose, helm_chart]
          description: Source type (K8s manifest, Helm chart, Docker compose)
        source_content:
          type: string
          format: byte
          description: Source content
        catalog_data:
          $ref: ../common.yml#/map_object
        created_at:
          $ref: ../common.yml#/time
        updated_at:
          $ref: ../common.yml#/time
    mesheryApplicationPage:
      allOf:
      - $ref: ../common.yml#/resultsPage
      - type: object
        properties:
          applications:
            type: array
            items:
              $ref: '#/components/schemas/mesheryApplication'

  requestBodies:
    mesheryApplicationRequestBody:
      properties:
        url:
          $ref: ../common.yml#/endpoint
        path:
          $ref: ../common.yml#/text
        save:
          type: boolean
        application_data:
          $ref: '#/components/schemas/mesheryApplication'
        source_type:
          $ref: ../common.yml#/text
          description: Source type (K8s manifest, Helm chart, Docker compose)

# any special parameters for this tag
  parameters:
# any special response for this tag
  responses:

  paths:
    #apps
    /api/content/applications:
      post:
        tags:
          - content
        operationId: UpsertApplication
        summary: Upsert Application
        description: It will insert the application if not present else it will update the matching entry
        requestBody:
          description: Body for upserting meshery application
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/requestBodies/mesheryApplicationRequestBody'
        responses:
          '200':
            description: Upserted application
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/mesheryApplication'
          '400':
            $ref: ../responses.yml#/400
          '401':
            $ref: ../responses.yml#/401
          '500':
            $ref: ../responses.yml#/500
      get:
        tags:
          - applications
        operationId: GetApplications
        summary: Get Applications
        description: Get paginated applications
        parameters:
          - $ref: ../parameters.yml#/page
          - $ref: ../parameters.yml#/pageSize
          - $ref: ../parameters.yml#/search
          - $ref: ../parameters.yml#/order
        responses:
          '200':
            description: Applications
            content:
              application/json:
                schema:
                  $ref: '#/mesheryApplicationPage'
          '401':
            $ref: ../responses.yml#/401
          '500':
            $ref: ../responses.yml#/500
    /api/content/applications/upload/{id}:
      post:
        tags:
          - content
        operationId: UpsertApplicationSourceContent
        summary: Upsert application source content
        description: Upserts only application source content
        parameters:
          - $ref: ../parameters.yml#/id
        requestBody:
          description: Body for upserting meshery application source content
          required: true
          content:
            text/plain:
              schema:
              $ref: '#/components/schemas/mesheryApplication/properties/source_content'
        responses:
          '200':
            $ref: ../responses.yml#/200
          '400':
            $ref: ../responses.yml#/400
          '401':
            $ref: ../responses.yml#/401
          '500':
            $ref: ../responses.yml#/500            
    /api/content/applications/download/{id}:
      get:
        tags:
          - content
        operationId: GetApplicationSourceContent
        summary: Get application source content
        description: Get application source content
        parameters:
          - $ref: ../parameters.yml#/id
        responses:
          '200':
            description: application source content associated with ID
            content:
              text/plain:
                schema:
                  $ref: '#/components/schemas/mesheryApplication/properties/source_content'
          '400':
            $ref: ../responses.yml#/400
          '401':
            $ref: ../responses.yml#/401
          '500':
            $ref: ../responses.yml#/500
    /api/content/applications/{id}:
      get:
        tags:
          - content
        operationId: GetApplication
        summary: Get application by ID
        description: Get application by ID
        parameters:
          - $ref: ../parameters.yml#/id
        responses:
          '200':
            description: application associated with ID
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/mesheryApplication'
          '400':
            $ref: ../responses.yml#/400
          '401':
            $ref: ../responses.yml#/401
          '404':
            $ref: ../responses.yml#/404
          '500':
            $ref: ../responses.yml#/500
      delete:
        tags:
          - content
        operationId: DeleteApplication
        summary: Delete application by ID
        description: Delete application associated with ID
        parameters:
          - $ref: ../parameters.yml#/id
        responses:
          '200':
            description: Deleted application
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/mesheryApplication'
          '400':
            $ref: ../responses.yml#/400
          '401':
            $ref: ../responses.yml#/401
          '404':
            $ref: ../responses.yml#/404
          '500':
            $ref: ../responses.yml#/500
