openapi: 3.0.0
info:
  title: Category
  description: OpenAPI schema for model category definitions in Meshery.
  version: v1beta1
  contact:
    name: Meshery Maintainers
    email: maintainers@meshery.io
    url: https://meshery.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
components:
  schemas:
    CategoryDefinition:
      $ref: "./category.yaml"
