openapi: 3.0.0
info:
  title: Component
  description: OpenAPI schema for component definitions in Meshery.
  version: v1beta2
  contact:
    name: Meshery Maintainers
    email: maintainers@meshery.io
    url: https://meshery.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
components:
  schemas:
    ComponentDefinition:
      $ref: "./component.yaml"

    Component:
      description: "Data related to the third-party capability that a ComponentDefinition wraps; this payload is treated as a hermetically sealed, opaque object."
      type: object
      properties:
        version:
          type: string
          description: "Version of the component produced by the registrant. Example: APIVersion of a Kubernetes Pod."
          x-order: 1
          maxLength: 500
        kind:
          type: string
          description: "The unique identifier (name) assigned by the registrant to this component. Example: A Kubernetes Pod is of kind 'Pod'."
          x-order: 2
          maxLength: 255
        schema:
          type: string
          description: "JSON schema of the object as defined by the registrant."
          x-order: 3
          maxLength: 500
      required:
        - version
        - kind
        - schema
