// Package meshsync provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package meshsync

import (
	patternv1beta1 "github.com/meshery/schemas/models/v1beta1/pattern"
)

// MeshSyncDeleteResponse Response returned after deleting a MeshSync resource.
type MeshSyncDeleteResponse struct {
	// Deleted Whether the MeshSync resource was deleted.
	Deleted *bool `json:"deleted,omitempty" yaml:"deleted,omitempty"`
}

// MeshSyncKeyValue A discovered Kubernetes key-value pair (e.g. a label).
type MeshSyncKeyValue struct {
	// Id MeshSync resource ID associated with this key-value pair.
	ID *string `json:"id,omitempty" yaml:"id,omitempty"`

	// Key The key of the key-value pair.
	Key *string `json:"key,omitempty" yaml:"key,omitempty"`

	// Kind Key-value kind, such as `label` or `annotation`.
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// UniqueId Internal unique identifier for this key-value pair.
	UniqueId *string `json:"uniqueId,omitempty" yaml:"uniqueId,omitempty"`

	// Value The value of the key-value pair.
	Value *string `json:"value,omitempty" yaml:"value,omitempty"`
}

// MeshSyncKindCount Per-kind resource count for a given model.
type MeshSyncKindCount struct {
	// Count Number of discovered resources of this kind.
	Count *int64 `json:"count,omitempty" yaml:"count,omitempty"`

	// Kind Kubernetes resource kind.
	Kind *string `json:"kind,omitempty" yaml:"kind,omitempty"`

	// Model Meshery model name that registered this kind.
	Model *string `json:"model,omitempty" yaml:"model,omitempty"`
}

// MeshSyncResourcesPage A paginated list of MeshSync-discovered Kubernetes resources.
type MeshSyncResourcesPage struct {
	// Design Designs are your primary tool for collaborative authorship of your infrastructure, workflow, and processes.
	Design *patternv1beta1.PatternFile `json:"design,omitempty" yaml:"design,omitempty"`

	// Page Current page number (zero-indexed).
	Page *int `json:"page,omitempty" yaml:"page,omitempty"`

	// PageSize Number of items in this page.
	PageSize *int `json:"pageSize,omitempty" yaml:"pageSize,omitempty"`

	// Resources The discovered Kubernetes resources. Empty when `asDesign` is true.
	Resources *[]map[string]interface{} `json:"resources,omitempty" yaml:"resources,omitempty"`

	// TotalCount Total number of matching resources across all pages.
	TotalCount *int64 `json:"totalCount,omitempty" yaml:"totalCount,omitempty"`
}

// MeshSyncResourcesSummary Summary of discovered MeshSync resources for the requested clusters.
type MeshSyncResourcesSummary struct {
	// Kinds Per-kind resource counts.
	Kinds *[]MeshSyncKindCount `json:"kinds,omitempty" yaml:"kinds,omitempty"`

	// Labels Distinct label key-value pairs found on discovered resources.
	Labels *[]MeshSyncKeyValue `json:"labels,omitempty" yaml:"labels,omitempty"`

	// Namespaces Distinct namespaces containing discovered resources.
	Namespaces *[]string `json:"namespaces,omitempty" yaml:"namespaces,omitempty"`
}

// Order defines model for order.
type Order = string

// Page defines model for page.
type Page = string

// PageSize defines model for pageSize.
type PageSize = string

// ResourceId defines model for resourceId.
type ResourceId = string

// Search defines model for search.
type Search = string
