/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Category of the model.
 */
export interface HttpsSchemasMesheryIoCategoryJson {
  /**
   * A Universally Unique Identifier used to uniquely identify entites in Meshery. The UUID core defintion is used across different schemas.
   */
  id: string;
  name: string;
  metadata: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
