openapi: 3.0.0
info:
  title: Credential API
  version: v1beta1
  description: API for managing Meshery credentials used to store sensitive information for connections.

paths:
  /api/integrations/credentials:
    get:
      x-internal: ["cloud"]
      tags:
        - Credentials
      operationId: GetUserCredentials
      summary: Get user credentials
      description: Returns a paginated list of credentials for the authenticated user.
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 0
        - name: pagesize
          in: query
          description: Number of credentials per page
          required: false
          schema:
            type: integer
            default: 10
            maximum: 25
        - name: search
          in: query
          description: Search filter for credential names
          required: false
          schema:
            type: string
        - name: order
          in: query
          description: Order by field (e.g., created_at desc)
          required: false
          schema:
            type: string
      responses:
        "200":
          description: A paginated list of credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CredentialPage"
        "500":
          description: Server error

    post:
      x-internal: ["cloud"]
      tags:
        - Credentials
      operationId: SaveUserCredential
      summary: Create a new credential
      description: Creates a new credential for the authenticated user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credential"
      responses:
        "201":
          description: Credential created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Credential"
        "500":
          description: Server error

    put:
      x-internal: ["cloud"]
      tags:
        - Credentials
      operationId: UpdateUserCredential
      summary: Update an existing credential
      description: Updates an existing credential for the authenticated user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credential"
      responses:
        "200":
          description: Credential updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Credential"
        "500":
          description: Server error

    delete:
      x-internal: ["cloud"]
      tags:
        - Credentials
      operationId: DeleteUserCredential
      summary: Delete a credential
      description: Soft deletes a credential by its ID.
      parameters:
        - name: credential_id
          in: query
          description: ID of the credential to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Credential deleted successfully
        "500":
          description: Server error

  /api/integrations/credentials/{id}:
    get:
      x-internal: ["cloud"]
      tags:
        - Credentials
      operationId: GetCredentialByID
      summary: Get a credential by ID
      description: Returns a specific credential by its ID.
      parameters:
        - name: id
          in: path
          description: Credential ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Credential details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Credential"
        "500":
          description: Server error

components:
  schemas:
    Credential:
      $ref: "./credential.yaml"
    CredentialPage:
      type: object
      description: Represents a page of credentials with pagination information
      required:
        - credentials
        - total_count
        - page
        - page_size
      properties:
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/Credential'
            x-go-type: '*Credential'
          x-oapi-codegen-extra-tags:
            json: credentials
        total_count:
          type: integer
          description: Total number of credentials across all pages
          x-oapi-codegen-extra-tags:
            json: total_count
        page:
          type: integer
          description: Current page number
          x-oapi-codegen-extra-tags:
            json: page
        page_size:
          type: integer
          description: Number of credentials per page
          x-oapi-codegen-extra-tags:
            json: page_size
