// Package blowhorn_ledger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package blowhorn_ledger

import (
	"time"

	core "github.com/meshery/schemas/models/core"
)

// BlowhornContact Server-returned Blowhorn contact as persisted by meshery-cloud. Contacts
// are upserted per platform handle and back the credential-less platform
// opt-in rows.
type BlowhornContact struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID core.Uuid `json:"id" yaml:"id"`

	// OrganizationId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	OrganizationID core.Uuid `db:"organization_id" json:"organizationId" yaml:"organizationId"`

	// Platform Platform the contact belongs to (e.g. linkedin, github).
	Platform string `db:"platform" json:"platform" yaml:"platform"`

	// Handle Platform-side handle identifying the contact. Unique per platform within the organization.
	Handle string `db:"handle" json:"handle" yaml:"handle"`

	// DisplayName Human-readable contact name.
	DisplayName *string `db:"display_name" json:"displayName,omitempty" yaml:"displayName,omitempty"`

	// ProfileUrl Platform-side profile URL for the contact.
	ProfileUrl *string `db:"profile_url" json:"profileUrl,omitempty" yaml:"profileUrl,omitempty"`

	// Metadata Contact metadata, stored as a JSON blob.
	Metadata  core.Map  `db:"metadata" json:"metadata,omitempty" yaml:"metadata,omitempty"`
	CreatedAt core.Time `db:"created_at" json:"createdAt" yaml:"createdAt"`
	UpdatedAt core.Time `db:"updated_at" json:"updatedAt" yaml:"updatedAt"`
}

// BlowhornContactPage Paginated collection of Blowhorn contacts.
type BlowhornContactPage struct {
	// BlowhornContacts Blowhorn contacts included on this page of results.
	BlowhornContacts *[]BlowhornContact `json:"blowhornContacts,omitempty" yaml:"blowhornContacts,omitempty"`

	// Page Current page number of the result set.
	Page *int `json:"page,omitempty" yaml:"page,omitempty"`

	// PageSize Number of items per page.
	PageSize *int `json:"pageSize,omitempty" yaml:"pageSize,omitempty"`

	// TotalCount Total number of items available.
	TotalCount *int `json:"totalCount,omitempty" yaml:"totalCount,omitempty"`
}

// BlowhornContactPayload Payload for creating or updating a Blowhorn contact. Contains
// only client-settable fields; the owning `organizationId` (derived
// from the authenticated session) and the server-generated
// `createdAt` / `updatedAt` timestamps are intentionally excluded.
type BlowhornContactPayload struct {
	// DisplayName Human-readable contact name.
	DisplayName *string `json:"displayName,omitempty" yaml:"displayName,omitempty"`

	// Handle Platform-side handle identifying the contact. Unique per platform within the organization.
	Handle string `json:"handle" yaml:"handle"`

	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID *core.Uuid `json:"id,omitempty" yaml:"id,omitempty"`

	// Metadata Contact metadata, stored as a JSON blob.
	Metadata core.Map `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Platform Platform the contact belongs to (e.g. linkedin, github).
	Platform string `json:"platform" yaml:"platform"`

	// ProfileUrl Platform-side profile URL for the contact.
	ProfileUrl *string `json:"profileUrl,omitempty" yaml:"profileUrl,omitempty"`
}

// BlowhornLedgerClaimRequest Claim-if-absent payload taking an unclaimed entry for a holder.
type BlowhornLedgerClaimRequest struct {
	// Holder Holder taking the entry. Refused with a 409 when the entry is already claimed.
	Holder string `json:"holder" yaml:"holder"`
}

// BlowhornLedgerEntry Server-returned Blowhorn ledger entry as persisted by meshery-cloud.
// Ledger entries form ledger-discriminated idempotent sets keyed by
// (ledger, key): recording the same pair replays idempotently, and
// claim-if-absent takes the entry for a holder exactly once.
type BlowhornLedgerEntry struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID core.Uuid `json:"id" yaml:"id"`

	// OrganizationId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	OrganizationID core.Uuid `db:"organization_id" json:"organizationId" yaml:"organizationId"`

	// Ledger Ledger discriminator naming the idempotent set.
	Ledger string `db:"ledger" json:"ledger" yaml:"ledger"`

	// EntryKey Key within the ledger. Unique per ledger.
	EntryKey string `db:"entry_key" json:"entryKey" yaml:"entryKey"`

	// Value Entry value, stored as a JSON blob.
	Value core.Map `db:"value" json:"value,omitempty" yaml:"value,omitempty"`

	// ClaimedBy Holder that claimed the entry, if any. Set only by claim-if-absent.
	ClaimedBy *string `db:"claimed_by" json:"claimedBy,omitempty" yaml:"claimedBy,omitempty"`

	// ClaimedAt Time the entry was claimed, if any. Set only by claim-if-absent.
	ClaimedAt time.Time `db:"claimed_at" json:"claimedAt,omitempty" yaml:"claimedAt,omitempty"`
	CreatedAt core.Time `db:"created_at" json:"createdAt" yaml:"createdAt"`
	UpdatedAt core.Time `db:"updated_at" json:"updatedAt" yaml:"updatedAt"`
}

// BlowhornLedgerPage Paginated collection of Blowhorn ledger entries.
type BlowhornLedgerPage struct {
	// BlowhornLedgerEntries Blowhorn ledger entries included on this page of results.
	BlowhornLedgerEntries *[]BlowhornLedgerEntry `json:"blowhornLedgerEntries,omitempty" yaml:"blowhornLedgerEntries,omitempty"`

	// Page Current page number of the result set.
	Page *int `json:"page,omitempty" yaml:"page,omitempty"`

	// PageSize Number of items per page.
	PageSize *int `json:"pageSize,omitempty" yaml:"pageSize,omitempty"`

	// TotalCount Total number of items available.
	TotalCount *int `json:"totalCount,omitempty" yaml:"totalCount,omitempty"`
}

// BlowhornLedgerPayload Payload for recording a Blowhorn ledger entry. Contains only
// client-settable fields; the owning `organizationId` (derived from
// the authenticated session), the claim columns and the
// server-generated `createdAt` / `updatedAt` timestamps are
// intentionally excluded.
type BlowhornLedgerPayload struct {
	// EntryKey Key within the ledger. Unique per ledger.
	EntryKey string `json:"entryKey" yaml:"entryKey"`

	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID *core.Uuid `json:"id,omitempty" yaml:"id,omitempty"`

	// Ledger Ledger discriminator naming the idempotent set.
	Ledger string `json:"ledger" yaml:"ledger"`

	// Value Entry value, stored as a JSON blob.
	Value core.Map `json:"value,omitempty" yaml:"value,omitempty"`
}

// BlowhornMentee Server-returned Blowhorn mentee as persisted by meshery-cloud. Mentees
// track mentored subjects through stages; recording a mentee and dropping
// it is a single operation that stamps the drop time.
type BlowhornMentee struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID core.Uuid `json:"id" yaml:"id"`

	// OrganizationId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	OrganizationID core.Uuid `db:"organization_id" json:"organizationId" yaml:"organizationId"`

	// Subject Mentored subject.
	Subject string `db:"subject" json:"subject" yaml:"subject"`

	// Stage Mentorship stage of the subject.
	Stage *string `db:"stage" json:"stage,omitempty" yaml:"stage,omitempty"`

	// Metadata Mentee metadata, stored as a JSON blob.
	Metadata core.Map `db:"metadata" json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// DroppedAt Time the mentee was recorded and dropped, if any. Set only by the record-and-drop operation.
	DroppedAt time.Time `db:"dropped_at" json:"droppedAt,omitempty" yaml:"droppedAt,omitempty"`
	CreatedAt core.Time `db:"created_at" json:"createdAt" yaml:"createdAt"`
	UpdatedAt core.Time `db:"updated_at" json:"updatedAt" yaml:"updatedAt"`
}

// BlowhornMenteeDropRequest Record-and-drop payload.
type BlowhornMenteeDropRequest struct {
	// Stage Final mentorship stage recorded with the drop.
	Stage *string `json:"stage,omitempty" yaml:"stage,omitempty"`
}

// BlowhornMenteePage Paginated collection of Blowhorn mentees.
type BlowhornMenteePage struct {
	// BlowhornMentees Blowhorn mentees included on this page of results.
	BlowhornMentees *[]BlowhornMentee `json:"blowhornMentees,omitempty" yaml:"blowhornMentees,omitempty"`

	// Page Current page number of the result set.
	Page *int `json:"page,omitempty" yaml:"page,omitempty"`

	// PageSize Number of items per page.
	PageSize *int `json:"pageSize,omitempty" yaml:"pageSize,omitempty"`

	// TotalCount Total number of items available.
	TotalCount *int `json:"totalCount,omitempty" yaml:"totalCount,omitempty"`
}

// BlowhornMenteePayload Payload for creating or updating a Blowhorn mentee. Contains only
// client-settable fields; the owning `organizationId` (derived from
// the authenticated session), the server-managed `droppedAt` and
// the server-generated `createdAt` / `updatedAt` timestamps are
// intentionally excluded.
type BlowhornMenteePayload struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID *core.Uuid `json:"id,omitempty" yaml:"id,omitempty"`

	// Metadata Mentee metadata, stored as a JSON blob.
	Metadata core.Map `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Stage Mentorship stage of the subject.
	Stage *string `json:"stage,omitempty" yaml:"stage,omitempty"`

	// Subject Mentored subject.
	Subject string `json:"subject" yaml:"subject"`
}

// BlowhornLedgerEntryId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type BlowhornLedgerEntryId = core.Uuid

// BlowhornMenteeId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type BlowhornMenteeId = core.Uuid

// Order defines model for order.
type Order = string

// Page defines model for page.
type Page = int

// PageSize defines model for pageSize.
type PageSize = int

// Pagesize defines model for pagesize.
type Pagesize = int

// Search defines model for search.
type Search = string
