openapi: 3.0.0
info:
  title: Capability
  description: OpenAPI schema for Meshery capability definitions.
  version: v1alpha1
  contact:
    name: Meshery Maintainers
    email: maintainers@meshery.io
    url: https://meshery.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
components:
  schemas:
    Capability:
      $ref: "./capability.yaml"
