openapi: 3.0.0
info:
  title: Catalog
  description: OpenAPI schema for Meshery catalog data and content management.
  x-deprecated: true
  x-superseded-by: v1beta2
  version: v1beta1
  contact:
    name: Meshery Maintainers
    email: maintainers@meshery.io
    url: https://meshery.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths: {}
components:
  schemas:
    CatalogData:
      $ref: "./catalog.yaml"
