openapi: 3.0.0
info:
  title: team
  description: Documentation for Team API
  version: v1beta1

security:
  - jwt: []

tags:
  - name: teams
    description: APIs for Teams

components:
  responses:
    200:
      $ref: "../../v1alpha1/core/api.yml#/components/responses/200"
    400:
      $ref: "../../v1alpha1/core/api.yml#/components/responses/400"
    401:
      $ref: "../../v1alpha1/core/api.yml#/components/responses/401"
    500:
      $ref: "../../v1alpha1/core/api.yml#/components/responses/500"

  parameters:
    teamId:
      name: teamId
      in: path
      description: Team ID
      schema:
        $ref: ../../v1alpha1/core/api.yml#/components/schemas/Id
      required: true
    orgId:
      name: orgId
      in: path
      description: Organization ID
      schema:
        $ref: ../../v1alpha1/core/api.yml#/components/schemas/Id
      required: true
    userId:
      name: userId
      in: path
      description: User ID
      schema:
        $ref: ../../v1alpha1/core/api.yml#/components/schemas/Id
      required: true
    search:
      $ref: ../../v1alpha1/core/api.yml#/components/parameters/search
    order:
      $ref: ../../v1alpha1/core/api.yml#/components/parameters/order
    page:
      $ref: ../../v1alpha1/core/api.yml#/components/parameters/page
    pagesize:
      $ref: ../../v1alpha1/core/api.yml#/components/parameters/pagesize

  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    team:
      $ref: "./team.yaml"
    teamPayload:
      properties:
        name:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/Text
          description: Team name. Provide a name that meaningfully represents this team.
        description:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/Text
          description: Team description. Provide a detailed description to clarify the purpose of this team.
        notifyTeamUpdate:
          type: boolean
          description: Whether to notify team members about updates
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            json: notify_team_update
        metadata:
          type: object
          x-go-type: slices.Map
          x-go-type-import:
            path: github.com/gobuffalo/pop/slices
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            json: metadata
      required:
        - name
    teamsPage:
      properties:
        page:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/number
        pageSize:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/number
          x-oapi-codegen-extra-tags:
            json: page_size
        totalCount:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/number
          x-oapi-codegen-extra-tags:
            json: total_count
        teams:
          type: array
          x-go-type-skip-optional-pointer: true
          items:
            x-go-type: Team
            $ref: "#/components/schemas/team"
    usersTeamsMapping:
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid
          x-go-type-skip-optional-pointer: true
          x-go-name: ID
          x-oapi-codegen-extra-tags:
            db: id
            json: ID
        userId:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid
          x-go-type-skip-optional-pointer: true
          x-go-name: UserId
          x-oapi-codegen-extra-tags:
            db: user_id
            json: user_id
        teamId:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid
          x-go-type-skip-optional-pointer: true
          x-go-name: TeamId
          x-oapi-codegen-extra-tags:
            db: team_id
            json: team_id
        roleId:
          type: string
          format: uuid
          x-go-type: nulls.UUID
          x-go-type-import:
            path: github.com/gobuffalo/nulls
          x-go-type-skip-optional-pointer: true
          x-go-name: RoleId
          x-oapi-codegen-extra-tags:
            db: role_id
            json: role_id
        createdAt:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/Time
          x-oapi-codegen-extra-tags:
            db: created_at
            json: created_at
        updatedAt:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/Time
          x-oapi-codegen-extra-tags:
            db: updated_at
            json: updated_at
        deletedAt:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/nullTime
          x-oapi-codegen-extra-tags:
            db: deleted_at
            json: deleted_at
    usersTeamsMappingPage:
      properties:
        page:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/number
        pageSize:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/number
          x-oapi-codegen-extra-tags:
            json: page_size
        totalCount:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/number
          x-oapi-codegen-extra-tags:
            json: total_count
        usersTeamsMapping:
          type: array
          x-go-type-skip-optional-pointer: true
          x-oapi-codegen-extra-tags:
            json: users_teams_mapping
          items:
            x-go-type: UsersTeamsMapping
            $ref: "#/components/schemas/usersTeamsMapping"
    teamsOrganizationsMapping:
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid
          x-go-type-skip-optional-pointer: true
          x-go-name: ID
          x-oapi-codegen-extra-tags:
            db: id
            json: ID
        organizationId:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid
          x-go-type-skip-optional-pointer: true
          x-go-name: OrganizationId
          x-oapi-codegen-extra-tags:
            db: organization_id
            json: organization_id
        teamId:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid
          x-go-type-skip-optional-pointer: true
          x-go-name: TeamId
          x-oapi-codegen-extra-tags:
            db: team_id
            json: team_id
        createdAt:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/Time
          x-oapi-codegen-extra-tags:
            db: created_at
            json: created_at
        updatedAt:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/Time
          x-oapi-codegen-extra-tags:
            db: updated_at
            json: updated_at
        deletedAt:
          $ref: ../../v1alpha1/core/api.yml#/components/schemas/nullTime
          x-oapi-codegen-extra-tags:
            db: deleted_at
            json: deleted_at

  requestBodies:
    teamPayload:
      description: Body for creating or updating a team
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/teamPayload"

paths:
  /api/identity/orgs/{orgId}/teams:
    get:
      x-internal: ["cloud"]
      tags:
        - teams
      operationId: getTeamsOfOrg
      summary: Get all teams of an organization
      description: Gets all teams associated with an organization
      parameters:
        - $ref: "#/components/parameters/orgId"
        - $ref: "#/components/parameters/search"
        - $ref: "#/components/parameters/order"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pagesize"
      responses:
        "200":
          description: Teams
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/teamsPage"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"
    post:
      x-internal: ["cloud"]
      tags:
        - teams
      operationId: createTeam
      summary: Create a team
      description: Creates a new team within an organization
      parameters:
        - $ref: "#/components/parameters/orgId"
      requestBody:
        $ref: "#/components/requestBodies/teamPayload"
      responses:
        "201":
          description: Created team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/teamsPage"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"

  /api/identity/orgs/{orgId}/teams/{teamId}:
    get:
      x-internal: ["cloud"]
      tags:
        - teams
      operationId: getTeamById
      summary: Get a team by ID
      description: Gets a team by its ID within an organization
      parameters:
        - $ref: "#/components/parameters/orgId"
        - $ref: "#/components/parameters/teamId"
      responses:
        "200":
          description: Team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/teamsPage"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"
    put:
      x-internal: ["cloud"]
      tags:
        - teams
      operationId: updateTeam
      summary: Update a team
      description: Updates a team within an organization
      parameters:
        - $ref: "#/components/parameters/orgId"
        - $ref: "#/components/parameters/teamId"
      requestBody:
        $ref: "#/components/requestBodies/teamPayload"
      responses:
        "200":
          description: Updated team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/teamsPage"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
    delete:
      x-internal: ["cloud"]
      tags:
        - teams
      operationId: deleteTeam
      summary: Delete a team
      description: Deletes a team within an organization
      parameters:
        - $ref: "#/components/parameters/orgId"
        - $ref: "#/components/parameters/teamId"
      responses:
        "200":
          description: Deleted team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/teamsPage"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"

  /api/identity/orgs/{orgId}/teams/{teamId}/users:
    get:
      x-internal: ["cloud"]
      tags:
        - teams
      operationId: getUsersOfTeam
      summary: Get users of a team
      description: Gets all users assigned to a team
      parameters:
        - $ref: "#/components/parameters/orgId"
        - $ref: "#/components/parameters/teamId"
        - $ref: "#/components/parameters/search"
        - $ref: "#/components/parameters/order"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pagesize"
      responses:
        "200":
          description: Users of team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/usersTeamsMappingPage"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"

  /api/identity/orgs/{orgId}/teams/{teamId}/users/{userId}:
    post:
      x-internal: ["cloud"]
      tags:
        - teams
      operationId: addUserToTeam
      summary: Add a user to a team
      description: Adds a user to a team within an organization
      parameters:
        - $ref: "#/components/parameters/orgId"
        - $ref: "#/components/parameters/teamId"
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: User added to team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/usersTeamsMappingPage"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
    delete:
      x-internal: ["cloud"]
      tags:
        - teams
      operationId: removeUserFromTeam
      summary: Remove a user from a team
      description: Removes a user from a team within an organization
      parameters:
        - $ref: "#/components/parameters/orgId"
        - $ref: "#/components/parameters/teamId"
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: User removed from team
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/usersTeamsMappingPage"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
