# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: organization

# Update the "output" and "include-tags" based on the resource for which code generation needs to be invoked.
generate:
  models: true
import-mapping:
  "./core.yml": ""
  "./common/core.yml": "github.com/meshery/schemas/models/core"
  "../core.json": "github.com/meshery/schemas/models/core"
  "./common/parameters.yml": "github.com/meshery/schemas/models/core"
  "../v1beta1/model.json": "github.com/meshery/schemas/models/v1beta1/model"
  "../v1beta1/component.json": "github.com/meshery/schemas/models/v1beta1/model"
  "../v1alpha1/capability.json": "github.com/meshery/schemas/models/v1alpha1/capability"

output: models/v1beta1/organization.go 
output-options:
  # name-normalizer: ToCamelCaseWithInitialisms
  skip-prune: true
  include-tags: 
  - organizations
  
