// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package user

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/gofrs/uuid"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRoleNames.
const (
	UserRoleNamesAdmin             UserRoleNames = "admin"
	UserRoleNamesCurator           UserRoleNames = "curator"
	UserRoleNamesMeshmap           UserRoleNames = "meshmap"
	UserRoleNamesOrganizationAdmin UserRoleNames = "organization admin"
	UserRoleNamesTeamAdmin         UserRoleNames = "team admin"
	UserRoleNamesUser              UserRoleNames = "user"
	UserRoleNamesWorkspaceAdmin    UserRoleNames = "workspace admin"
	UserRoleNamesWorkspaceManager  UserRoleNames = "workspace manager"
)

// Defines values for UserStatus.
const (
	Active    UserStatus = "active"
	Anonymous UserStatus = "anonymous"
	Inactive  UserStatus = "inactive"
	Pending   UserStatus = "pending"
)

// Adapter Placeholder for Adapter struct definition.
type Adapter = map[string]interface{}

// Grafana defines model for Grafana.
type Grafana struct {
	GrafanaAPIKey         *string `json:"grafanaAPIKey,omitempty" yaml:"grafanaAPIKey,omitempty"`
	GrafanaURL            *string `json:"grafanaURL,omitempty" yaml:"grafanaURL,omitempty"`
	SelectedBoardsConfigs *[]struct {
		// Board Placeholder for GrafanaBoard definition (define fields as needed)
		Board        *map[string]interface{}   `json:"board,omitempty" yaml:"board,omitempty"`
		Panels       *[]map[string]interface{} `json:"panels,omitempty" yaml:"panels,omitempty"`
		TemplateVars *[]string                 `json:"templateVars,omitempty" yaml:"templateVars,omitempty"`
	} `json:"selectedBoardsConfigs,omitempty" yaml:"selectedBoardsConfigs,omitempty"`
}

// GrafanaBoard Placeholder for GrafanaBoard definition (define fields as needed)
type GrafanaBoard = map[string]interface{}

// LoadTestPreferences defines model for LoadTestPreferences.
type LoadTestPreferences struct {
	// C Concurrent requests
	C *int `json:"c,omitempty" yaml:"c,omitempty"`

	// Gen Load generator
	Gen *string `json:"gen,omitempty" yaml:"gen,omitempty"`

	// Qps Queries per second
	Qps *int `json:"qps,omitempty" yaml:"qps,omitempty"`

	// T Duration
	T *string `json:"t,omitempty" yaml:"t,omitempty"`
}

// Panel Grafana panel structure imported from github.com/grafana-tools/sdk
type Panel = map[string]interface{}

// Preference defines model for Preference.
type Preference struct {
	AnonymousPerfResults              bool                    `json:"anonymousPerfResults" yaml:"anonymousPerfResults"`
	AnonymousUsageStats               bool                    `json:"anonymousUsageStats" yaml:"anonymousUsageStats"`
	DashboardPreferences              map[string]interface{}  `json:"dashboardPreferences" yaml:"dashboardPreferences"`
	Grafana                           *Grafana                `json:"grafana,omitempty" yaml:"grafana,omitempty"`
	LoadTestPrefs                     *LoadTestPreferences    `json:"loadTestPrefs,omitempty" yaml:"loadTestPrefs,omitempty"`
	MeshAdapters                      *[]Adapter              `json:"meshAdapters,omitempty" yaml:"meshAdapters,omitempty"`
	Prometheus                        *Prometheus             `json:"prometheus,omitempty" yaml:"prometheus,omitempty"`
	RemoteProviderPreferences         *map[string]interface{} `json:"remoteProviderPreferences,omitempty" yaml:"remoteProviderPreferences,omitempty"`
	SelectedOrganizationID            string                  `json:"selectedOrganizationID" yaml:"selectedOrganizationID"`
	SelectedWorkspaceForOrganizations map[string]string       `json:"selectedWorkspaceForOrganizations" yaml:"selectedWorkspaceForOrganizations"`
	UpdatedAt                         *time.Time              `json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
	UsersExtensionPreferences         map[string]interface{}  `json:"usersExtensionPreferences" yaml:"usersExtensionPreferences"`
}

// Prometheus defines model for Prometheus.
type Prometheus struct {
	PrometheusURL                   *string `json:"prometheusURL,omitempty" yaml:"prometheusURL,omitempty"`
	SelectedPrometheusBoardsConfigs *[]struct {
		// Board Placeholder for GrafanaBoard definition (define fields as needed)
		Board        *map[string]interface{}   `json:"board,omitempty" yaml:"board,omitempty"`
		Panels       *[]map[string]interface{} `json:"panels,omitempty" yaml:"panels,omitempty"`
		TemplateVars *[]string                 `json:"templateVars,omitempty" yaml:"templateVars,omitempty"`
	} `json:"selectedPrometheusBoardsConfigs,omitempty" yaml:"selectedPrometheusBoardsConfigs,omitempty"`
}

// SelectedGrafanaConfig defines model for SelectedGrafanaConfig.
type SelectedGrafanaConfig struct {
	// Board Placeholder for GrafanaBoard definition (define fields as needed)
	Board        *map[string]interface{}   `json:"board,omitempty" yaml:"board,omitempty"`
	Panels       *[]map[string]interface{} `json:"panels,omitempty" yaml:"panels,omitempty"`
	TemplateVars *[]string                 `json:"templateVars,omitempty" yaml:"templateVars,omitempty"`
}

// User Represents a user in Layer5 Cloud (Meshery)
type User struct {
	// AcceptedTermsAt Timestamp when user accepted terms and conditions
	AcceptedTermsAt time.Time `json:"accepted_terms_at,omitempty" yaml:"accepted_terms_at,omitempty"`

	// AvatarUrl URL to user's avatar image
	AvatarUrl *string `json:"avatar_url,omitempty" yaml:"avatar_url,omitempty"`

	// Bio User's biography or description
	Bio *string `json:"bio,omitempty" yaml:"bio,omitempty"`

	// Country User's country information stored as JSONB
	Country *map[string]interface{} `json:"country,omitempty" yaml:"country,omitempty"`

	// CreatedAt Timestamp when the user record was created
	CreatedAt time.Time `json:"created_at" yaml:"created_at"`

	// DeletedAt Timestamp when the user record was soft-deleted (null if not deleted)
	DeletedAt *time.Time `json:"deleted_at" yaml:"deleted_at"`

	// Email User's email address
	Email openapi_types.Email `json:"email" yaml:"email"`

	// FirstLoginTime Timestamp of user's first login
	FirstLoginTime time.Time `json:"first_login_time,omitempty" yaml:"first_login_time,omitempty"`

	// FirstName User's first name
	FirstName string `json:"first_name" yaml:"first_name"`

	// Id Unique identifier for the user
	Id uuid.UUID `json:"id" yaml:"id"`

	// LastLoginTime Timestamp of user's most recent login
	LastLoginTime time.Time `json:"last_login_time" yaml:"last_login_time"`

	// LastName User's last name
	LastName string `json:"last_name" yaml:"last_name"`

	// Organizations Organizations the user belongs to with role information
	Organizations *struct {
		OrganizationsWithRoles *[]map[string]interface{} `json:"organizations_with_roles,omitempty" yaml:"organizations_with_roles,omitempty"`
		TotalCount             *int                      `json:"total_count,omitempty" yaml:"total_count,omitempty"`
	} `json:"organizations,omitempty" yaml:"organizations,omitempty"`

	// Preferences User preferences stored as JSONB. Can contain arbitrary key-value pairs for user settings and configurations
	Preferences *User_Preferences `json:"preferences,omitempty" yaml:"preferences,omitempty"`

	// Provider Authentication provider (e.g., Layer5 Cloud, Twitter, Facebook, Github)
	Provider string `json:"provider" yaml:"provider"`

	// Region User's region information stored as JSONB
	Region *map[string]interface{} `json:"region,omitempty" yaml:"region,omitempty"`

	// RoleNames List of global roles assigned to the user
	RoleNames *[]UserRoleNames `json:"role_names,omitempty" yaml:"role_names,omitempty"`

	// Status User account status
	Status UserStatus `json:"status" yaml:"status"`

	// Teams Teams the user belongs to with role information
	Teams *struct {
		TeamsWithRoles *[]map[string]interface{} `json:"teams_with_roles,omitempty" yaml:"teams_with_roles,omitempty"`
		TotalCount     *int                      `json:"total_count,omitempty" yaml:"total_count,omitempty"`
	} `json:"teams,omitempty" yaml:"teams,omitempty"`

	// UpdatedAt Timestamp when the user record was last updated
	UpdatedAt time.Time `json:"updated_at" yaml:"updated_at"`

	// UserId User identifier (username or external ID)
	UserId string `json:"user_id" yaml:"user_id"`
}

// User_Preferences User preferences stored as JSONB. Can contain arbitrary key-value pairs for user settings and configurations
type User_Preferences struct {
	// AnonymousPerfResults Whether to collect anonymous performance results
	AnonymousPerfResults *bool `json:"anonymousPerfResults,omitempty" yaml:"anonymousPerfResults,omitempty"`

	// AnonymousUsageStats Whether to collect anonymous usage statistics
	AnonymousUsageStats *bool `json:"anonymousUsageStats,omitempty" yaml:"anonymousUsageStats,omitempty"`

	// DashboardPreferences Dashboard preferences
	DashboardPreferences *map[string]interface{} `json:"dashboardPreferences,omitempty" yaml:"dashboardPreferences,omitempty"`

	// Grafana Grafana configuration
	Grafana *struct {
		GrafanaAPIKey         *string                   `json:"grafanaAPIKey,omitempty" yaml:"grafanaAPIKey,omitempty"`
		GrafanaURL            *string                   `json:"grafanaURL,omitempty" yaml:"grafanaURL,omitempty"`
		SelectedBoardsConfigs *[]map[string]interface{} `json:"selectedBoardsConfigs,omitempty" yaml:"selectedBoardsConfigs,omitempty"`
	} `json:"grafana,omitempty" yaml:"grafana,omitempty"`

	// LoadTestPrefs Load test preferences
	LoadTestPrefs *struct {
		// C Concurrent requests
		C *int `json:"c,omitempty" yaml:"c,omitempty"`

		// Gen Load generator
		Gen *string `json:"gen,omitempty" yaml:"gen,omitempty"`

		// Qps Queries per second
		Qps *int `json:"qps,omitempty" yaml:"qps,omitempty"`

		// T Duration
		T *string `json:"t,omitempty" yaml:"t,omitempty"`
	} `json:"loadTestPrefs,omitempty" yaml:"loadTestPrefs,omitempty"`

	// MeshAdapters Mesh adapters configuration
	MeshAdapters *[]map[string]interface{} `json:"meshAdapters,omitempty" yaml:"meshAdapters,omitempty"`

	// NotifyRoleChange Whether user wants to be notified of role changes
	NotifyRoleChange *bool `json:"notify_role_change,omitempty" yaml:"notify_role_change,omitempty"`

	// Prometheus Prometheus configuration
	Prometheus *struct {
		PrometheusURL                   *string                   `json:"prometheusURL,omitempty" yaml:"prometheusURL,omitempty"`
		SelectedPrometheusBoardsConfigs *[]map[string]interface{} `json:"selectedPrometheusBoardsConfigs,omitempty" yaml:"selectedPrometheusBoardsConfigs,omitempty"`
	} `json:"prometheus,omitempty" yaml:"prometheus,omitempty"`

	// RemoteProviderPreferences Remote provider preferences
	RemoteProviderPreferences *map[string]interface{} `json:"remoteProviderPreferences,omitempty" yaml:"remoteProviderPreferences,omitempty"`

	// SelectedOrganizationID Currently selected organization ID
	SelectedOrganizationID *string `json:"selectedOrganizationID,omitempty" yaml:"selectedOrganizationID,omitempty"`

	// SelectedWorkspaceForOrganizations Selected workspace for each organization
	SelectedWorkspaceForOrganizations *map[string]string `json:"selectedWorkspaceForOrganizations,omitempty" yaml:"selectedWorkspaceForOrganizations,omitempty"`

	// UsersExtensionPreferences User extension preferences
	UsersExtensionPreferences *map[string]interface{} `json:"usersExtensionPreferences,omitempty" yaml:"usersExtensionPreferences,omitempty"`

	// WelcomeEmail Whether user wants to receive welcome emails
	WelcomeEmail         *bool                  `json:"welcome_email,omitempty" yaml:"welcome_email,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-" yaml:"-"`
}

// UserRoleNames defines model for User.RoleNames.
type UserRoleNames string

// UserStatus User account status
type UserStatus string

// Getter for additional properties for User_Preferences. Returns the specified
// element and whether it was found
func (a User_Preferences) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for User_Preferences
func (a *User_Preferences) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for User_Preferences to handle AdditionalProperties
func (a *User_Preferences) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["anonymousPerfResults"]; found {
		err = json.Unmarshal(raw, &a.AnonymousPerfResults)
		if err != nil {
			return fmt.Errorf("error reading 'anonymousPerfResults': %w", err)
		}
		delete(object, "anonymousPerfResults")
	}

	if raw, found := object["anonymousUsageStats"]; found {
		err = json.Unmarshal(raw, &a.AnonymousUsageStats)
		if err != nil {
			return fmt.Errorf("error reading 'anonymousUsageStats': %w", err)
		}
		delete(object, "anonymousUsageStats")
	}

	if raw, found := object["dashboardPreferences"]; found {
		err = json.Unmarshal(raw, &a.DashboardPreferences)
		if err != nil {
			return fmt.Errorf("error reading 'dashboardPreferences': %w", err)
		}
		delete(object, "dashboardPreferences")
	}

	if raw, found := object["grafana"]; found {
		err = json.Unmarshal(raw, &a.Grafana)
		if err != nil {
			return fmt.Errorf("error reading 'grafana': %w", err)
		}
		delete(object, "grafana")
	}

	if raw, found := object["loadTestPrefs"]; found {
		err = json.Unmarshal(raw, &a.LoadTestPrefs)
		if err != nil {
			return fmt.Errorf("error reading 'loadTestPrefs': %w", err)
		}
		delete(object, "loadTestPrefs")
	}

	if raw, found := object["meshAdapters"]; found {
		err = json.Unmarshal(raw, &a.MeshAdapters)
		if err != nil {
			return fmt.Errorf("error reading 'meshAdapters': %w", err)
		}
		delete(object, "meshAdapters")
	}

	if raw, found := object["notify_role_change"]; found {
		err = json.Unmarshal(raw, &a.NotifyRoleChange)
		if err != nil {
			return fmt.Errorf("error reading 'notify_role_change': %w", err)
		}
		delete(object, "notify_role_change")
	}

	if raw, found := object["prometheus"]; found {
		err = json.Unmarshal(raw, &a.Prometheus)
		if err != nil {
			return fmt.Errorf("error reading 'prometheus': %w", err)
		}
		delete(object, "prometheus")
	}

	if raw, found := object["remoteProviderPreferences"]; found {
		err = json.Unmarshal(raw, &a.RemoteProviderPreferences)
		if err != nil {
			return fmt.Errorf("error reading 'remoteProviderPreferences': %w", err)
		}
		delete(object, "remoteProviderPreferences")
	}

	if raw, found := object["selectedOrganizationID"]; found {
		err = json.Unmarshal(raw, &a.SelectedOrganizationID)
		if err != nil {
			return fmt.Errorf("error reading 'selectedOrganizationID': %w", err)
		}
		delete(object, "selectedOrganizationID")
	}

	if raw, found := object["selectedWorkspaceForOrganizations"]; found {
		err = json.Unmarshal(raw, &a.SelectedWorkspaceForOrganizations)
		if err != nil {
			return fmt.Errorf("error reading 'selectedWorkspaceForOrganizations': %w", err)
		}
		delete(object, "selectedWorkspaceForOrganizations")
	}

	if raw, found := object["usersExtensionPreferences"]; found {
		err = json.Unmarshal(raw, &a.UsersExtensionPreferences)
		if err != nil {
			return fmt.Errorf("error reading 'usersExtensionPreferences': %w", err)
		}
		delete(object, "usersExtensionPreferences")
	}

	if raw, found := object["welcome_email"]; found {
		err = json.Unmarshal(raw, &a.WelcomeEmail)
		if err != nil {
			return fmt.Errorf("error reading 'welcome_email': %w", err)
		}
		delete(object, "welcome_email")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for User_Preferences to handle AdditionalProperties
func (a User_Preferences) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AnonymousPerfResults != nil {
		object["anonymousPerfResults"], err = json.Marshal(a.AnonymousPerfResults)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'anonymousPerfResults': %w", err)
		}
	}

	if a.AnonymousUsageStats != nil {
		object["anonymousUsageStats"], err = json.Marshal(a.AnonymousUsageStats)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'anonymousUsageStats': %w", err)
		}
	}

	if a.DashboardPreferences != nil {
		object["dashboardPreferences"], err = json.Marshal(a.DashboardPreferences)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dashboardPreferences': %w", err)
		}
	}

	if a.Grafana != nil {
		object["grafana"], err = json.Marshal(a.Grafana)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'grafana': %w", err)
		}
	}

	if a.LoadTestPrefs != nil {
		object["loadTestPrefs"], err = json.Marshal(a.LoadTestPrefs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'loadTestPrefs': %w", err)
		}
	}

	if a.MeshAdapters != nil {
		object["meshAdapters"], err = json.Marshal(a.MeshAdapters)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'meshAdapters': %w", err)
		}
	}

	if a.NotifyRoleChange != nil {
		object["notify_role_change"], err = json.Marshal(a.NotifyRoleChange)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'notify_role_change': %w", err)
		}
	}

	if a.Prometheus != nil {
		object["prometheus"], err = json.Marshal(a.Prometheus)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'prometheus': %w", err)
		}
	}

	if a.RemoteProviderPreferences != nil {
		object["remoteProviderPreferences"], err = json.Marshal(a.RemoteProviderPreferences)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'remoteProviderPreferences': %w", err)
		}
	}

	if a.SelectedOrganizationID != nil {
		object["selectedOrganizationID"], err = json.Marshal(a.SelectedOrganizationID)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'selectedOrganizationID': %w", err)
		}
	}

	if a.SelectedWorkspaceForOrganizations != nil {
		object["selectedWorkspaceForOrganizations"], err = json.Marshal(a.SelectedWorkspaceForOrganizations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'selectedWorkspaceForOrganizations': %w", err)
		}
	}

	if a.UsersExtensionPreferences != nil {
		object["usersExtensionPreferences"], err = json.Marshal(a.UsersExtensionPreferences)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'usersExtensionPreferences': %w", err)
		}
	}

	if a.WelcomeEmail != nil {
		object["welcome_email"], err = json.Marshal(a.WelcomeEmail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'welcome_email': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
