/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sub category of the model determines the secondary grouping.
 */
export type SubCategory =
  | "API Gateway"
  | "API Integration"
  | "Application Definition & Image Build"
  | "Automation & Configuration"
  | "Certified Kubernetes - Distribution"
  | "Chaos Engineering"
  | "Cloud Native Storage"
  | "Cloud Provider"
  | "CNI"
  | "Compute"
  | "Container Registry"
  | "Container Runtime"
  | "Container Security"
  | "Container"
  | "Content Delivery Network"
  | "Continuous Integration & Delivery"
  | "Coordination & Service Discovery"
  | "Database"
  | "Flowchart"
  | "Framework"
  | "Installable Platform"
  | "Key Management"
  | "Key Management Service"
  | "Kubernetes"
  | "Logging"
  | "Machine Learning"
  | "Management Governance"
  | "Metrics"
  | "Monitoring"
  | "Networking Content Delivery"
  | "Operating System"
  | "Query"
  | "Remote Procedure Call"
  | "Scheduling & Orchestration"
  | "Secrets Management"
  | "Security Identity & Compliance"
  | "Service Mesh"
  | "Service Proxy"
  | "Source Version Control"
  | "Storage"
  | "Specifications"
  | "Streaming & Messaging"
  | "Tools"
  | "Tracing"
  | "Uncategorized"
  | "Video Conferencing";
/**
 * Visualization styles for a component
 */
export type ComponentStyles = Styles & {
  /**
   * The shape of the node's body. Note that each shape fits within the specified width and height, and so you may have to adjust width and height if you desire an equilateral shape (i.e. width !== height for several equilateral shapes)
   */
  shape?:
    | "ellipse"
    | "triangle"
    | "round-triangle"
    | "rectangle"
    | "round-rectangle"
    | "bottom-round-rectangle"
    | "cut-rectangle"
    | "barrel"
    | "rhomboid"
    | "diamond"
    | "round-diamond"
    | "pentagon"
    | "round-pentagon"
    | "hexagon"
    | "round-hexagon"
    | "concave-hexagon"
    | "heptagon"
    | "round-heptagon"
    | "octagon"
    | "round-octagon"
    | "star"
    | "tag"
    | "round-tag"
    | "vee"
    | "polygon";
  /**
   * The position of the node. If the position is set, the node is drawn at that position in the given dimensions. If the position is not set, the node is drawn at a random position.
   */
  position?: {
    /**
     * The x-coordinate of the node.
     */
    x: number;
    /**
     * The y-coordinate of the node.
     */
    y: number;
  };
  /**
   * The text to display for an element's body. Can give a path, e.g. data(id) will label with the elements id
   */
  "body-text"?: string;
  /**
   * How to wrap the text in the node. Can be 'none', 'wrap', or 'ellipsis'.
   */
  "body-text-wrap"?: string;
  /**
   * The maximum width for wrapping text in the node.
   */
  "body-text-max-width"?: string;
  /**
   * The opacity of the node's body text, including its outline.
   */
  "body-text-opacity"?: number;
  /**
   * The colour of the node's body text background. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "body-text-background-color"?: string;
  /**
   * The size of the node's body text.
   */
  "body-text-font-size"?: number;
  /**
   * The colour of the node's body text. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "body-text-color"?: string;
  /**
   * A CSS font weight to be applied to the node's body text.
   */
  "body-text-font-weight"?: string;
  /**
   * A CSS horizontal alignment to be applied to the node's body text.
   */
  "body-text-horizontal-align"?: string;
  /**
   * A CSS text decoration to be applied to the node's body text.
   */
  "body-text-decoration"?: string;
  /**
   * A CSS vertical alignment to be applied to the node's body text.
   */
  "body-text-vertical-align"?: string;
  /**
   * The width of the node's body or the width of an edge's line.
   */
  width?: number;
  /**
   * The height of the node's body
   */
  height?: number;
  /**
   * The URL that points to the image to show in the node.
   */
  "background-image"?: string;
  /**
   * The colour of the node's body. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "background-color"?: string;
  /**
   * Blackens the node's body for values from 0 to 1; whitens the node's body for values from 0 to -1.
   */
  "background-blacken"?: number;
  /**
   * The opacity level of the node's background colour
   */
  "background-opacity"?: number;
  /**
   * The x position of the background image, measured in percent (e.g. 50%) or pixels (e.g. 10px)
   */
  "background-position-x"?: string;
  /**
   * The y position of the background image, measured in percent (e.g. 50%) or pixels (e.g. 10px)
   */
  "background-position-y"?: string;
  /**
   * The x offset of the background image, measured in percent (e.g. 50%) or pixels (e.g. 10px)
   */
  "background-offset-x"?: string;
  /**
   * The y offset of the background image, measured in percent (e.g. 50%) or pixels (e.g. 10px)
   */
  "background-offset-y"?: string;
  /**
   * How the background image is fit to the node. Can be 'none', 'contain', or 'cover'.
   */
  "background-fit"?: string;
  /**
   * How the background image is clipped to the node. Can be 'none', 'node', or 'node-border'.
   */
  "background-clip"?: string;
  /**
   * How the background image's width is determined. Can be 'none', 'inner', or 'outer'.
   */
  "background-width-relative-to"?: string;
  /**
   * How the background image's height is determined. Can be 'none', 'inner', or 'outer'.
   */
  "background-height-relative-to"?: string;
  /**
   * The size of the node's border.
   */
  "border-width"?: number;
  /**
   * The style of the node's border
   */
  "border-style"?: "solid" | "dotted" | "dashed" | "double";
  /**
   * The colour of the node's border. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "border-color"?: string;
  /**
   * The opacity of the node's border
   */
  "border-opacity"?: number;
  /**
   * The amount of padding around all sides of the node.
   */
  padding?: number;
  /**
   * The horizontal alignment of a node's label
   */
  "text-halign"?: "left" | "center" | "right";
  /**
   * The vertical alignment of a node's label
   */
  "text-valign"?: "top" | "center" | "bottom";
  /**
   * Whether to use the ghost effect, a semitransparent duplicate of the element drawn at an offset.
   */
  ghost?: "yes" | "no";
  /**
   * The colour of the indicator shown when the background is grabbed by the user. Selector needs to be *core*. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "active-bg-color"?: string;
  /**
   * The opacity of the active background indicator. Selector needs to be *core*.
   */
  "active-bg-opacity"?: string;
  /**
   * The opacity of the active background indicator. Selector needs to be *core*.
   */
  "active-bg-size"?: string;
  /**
   * The background colour of the selection box used for drag selection. Selector needs to be *core*. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "selection-box-color"?: string;
  /**
   * The size of the border on the selection box. Selector needs to be *core*
   */
  "selection-box-border-width"?: number;
  /**
   * The opacity of the selection box. Selector needs to be *core*
   */
  "selection-box-opacity"?: number;
  /**
   * The colour of the area outside the viewport texture when initOptions.textureOnViewport === true. Selector needs to be *core*. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "outside-texture-bg-color"?: string;
  /**
   * The opacity of the area outside the viewport texture. Selector needs to be *core*
   */
  "outside-texture-bg-opacity"?: number;
  /**
   * An array (or a space-separated string) of numbers ranging on [-1, 1], representing alternating x and y values (i.e. x1 y1 x2 y2, x3 y3 ...). This represents the points in the polygon for the node's shape. The bounding box of the node is given by (-1, -1), (1, -1), (1, 1), (-1, 1). The node's position is the origin (0, 0 )
   */
  "shape-polygon-points"?: string;
  /**
   * The colour of the background of the component menu. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "menu-background-color"?: string;
  /**
   * The opacity of the background of the component menu.
   */
  "menu-background-opacity"?: number;
  /**
   * The colour of the text or icons in the component menu. Colours may be specified by name (e.g. red), hex (e.g.
   */
  "menu-forground-color"?: string;
  [k: string]: unknown;
};

/**
 * Components are reusable building blocks for depicting capabilities defined within models. Learn more at https://docs.meshery.io/concepts/components
 */
export interface HttpsSchemasMesheryIoComponentJson {
  /**
   * Uniquely identifies the entity (i.e. component) as defined in a declaration (i.e. design).
   */
  id: string;
  /**
   * Specifies the version of the schema to which the component definition conforms.
   */
  schemaVersion: string;
  /**
   * Version of the component definition.
   */
  version: string;
  /**
   * Name of the component in human-readible format.
   */
  displayName: string;
  /**
   * A written representation of the purpose and characteristics of the component.
   */
  description: string;
  /**
   * Format specifies the format used in the `component.schema` field. JSON is the default.
   */
  format: "JSON" | "CUE";
  model?: HttpsSchemasMesheryIoModelJson;
  modelReference: ModelReference;
  /**
   * A Universally Unique Identifier used to uniquely identify entites in Meshery. The UUID core defintion is used across different schemas.
   */
  modelId: string;
  styles?: ComponentStyles;
  /**
   * Meshery manages components in accordance with their specific capabilities. This field explicitly identifies those capabilities largely by what actions a given component supports; e.g. metric-scrape, sub-interface, and so on. This field is extensible. ComponentDefinitions may define a broad array of capabilities, which are in-turn dynamically interpretted by Meshery for full lifecycle management.
   */
  capabilities?: HttpsSchemasMesheryIoCapabilityJson1[];
  /**
   * Status of component, including:
   * - duplicate: this component is a duplicate of another. The component that is to be the canonical reference and that is duplicated by other components should not be assigned the 'duplicate' status.
   * - maintenance: model is unavailable for a period of time.
   * - enabled: model is available for use for all users of this Meshery Server.
   * - ignored: model is unavailable for use for all users of this Meshery Server.
   */
  status?: "ignored" | "enabled" | "duplicate" | "resolved" | "open";
  /**
   * Metadata contains additional information associated with the component.
   */
  metadata: {
    /**
     * Genealogy represents the various representational states of the component.
     */
    genealogy: string;
    /**
     * Identifies whether the component is semantically meaningful or not; identifies whether the component should be treated as deployable entity or is for purposes of logical representation.
     */
    isAnnotation: boolean;
    /**
     * Identifies whether the component is scoped to namespace or clsuter wide.
     */
    isNamespaced: boolean;
    /**
     * 'published' controls whether the component should be registered in Meshery Registry. When the same 'published' property in Models, is set to 'false', the Model property takes precedence with all Entities in the Model not being registered.
     */
    published: boolean;
    /**
     * InstanceDetails contains information about the instance of the component.
     */
    instanceDetails: {
      [k: string]: unknown;
    };
    /**
     * Defines the UI schema for rendering the component's configuration. For more details, visit: https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema/ .
     */
    configurationUISchema: string;
    [k: string]: unknown;
  };
  /**
   * The configuration of the component. The configuration is based on the schema defined within the component definition(component.schema).
   */
  configuration: {
    [k: string]: unknown;
  };
  component: Component;
  created_at?: string;
  updated_at?: string;
}
/**
 * Reference to the specific registered model to which the component belongs and from which model version, category, and other properties may be referenced. Learn more at https://docs.meshery.io/concepts/models
 */
export interface HttpsSchemasMesheryIoModelJson {
  /**
   * Uniquely identifies the entity (i.e. component) as defined in a declaration (i.e. design).
   */
  id: string;
  /**
   * Specifies the version of the schema used for the definition.
   */
  schemaVersion: string;
  /**
   * Version of the model definition.
   */
  version: string;
  /**
   * The unique name for the model within the scope of a registrant.
   */
  name: string;
  /**
   * Human-readable name for the model.
   */
  displayName: string;
  /**
   * Description of the model.
   */
  description: string;
  /**
   * Status of model, including:
   * - duplicate: this component is a duplicate of another. The component that is to be the canonical reference and that is duplicated by other components should not be assigned the 'duplicate' status.
   * - maintenance: model is unavailable for a period of time.
   * - enabled: model is available for use for all users of this Meshery Server.
   * - ignored: model is unavailable for use for all users of this Meshery Server.
   */
  status: "ignored" | "enabled" | "duplicate";
  registrant: HttpsSchemasMesheryIoComponentJson1;
  /**
   * ID of the registrant.
   */
  registrantId: string;
  /**
   * ID of the category.
   */
  categoryId: string;
  category: HttpsSchemasMesheryIoCategoryJson;
  subCategory: SubCategory;
  /**
   * Metadata containing additional information associated with the model.
   */
  metadata?: {
    /**
     * Capabilities associated with the model
     */
    capabilities?: HttpsSchemasMesheryIoCapabilityJson[];
    /**
     * Indicates whether the model and its entities should be treated as deployable entities or as logical representations.
     */
    isAnnotation?: boolean;
    /**
     * Primary color associated with the model.
     */
    primaryColor?: string;
    /**
     * Secondary color associated with the model.
     */
    secondaryColor?: string;
    /**
     * SVG representation of the model in white color.
     */
    svgWhite: string;
    /**
     * SVG representation of the model in colored format.
     */
    svgColor: string;
    /**
     * SVG representation of the complete model.
     */
    svgComplete?: string;
    /**
     * The shape of the node’s body. Note that each shape fits within the specified width and height, and so you may have to adjust width and height if you desire an equilateral shape (i.e. width !== height for several equilateral shapes)
     */
    shape?:
      | "circle"
      | "ellipse"
      | "triangle"
      | "round-triangle"
      | "rectangle"
      | "round-rectangle"
      | "bottom-round-rectangle"
      | "cut-rectangle"
      | "barrel"
      | "rhomboid"
      | "diamond"
      | "round-diamond"
      | "pentagon"
      | "round-pentagon"
      | "hexagon"
      | "round-hexagon"
      | "concave-hexagon"
      | "heptagon"
      | "round-heptagon"
      | "octagon"
      | "round-octagon"
      | "star"
      | "tag"
      | "round-tag"
      | "vee"
      | "polygon";
    [k: string]: unknown;
  };
  model: Model;
  relationships: unknown[];
  components: unknown[];
  /**
   * Number of components associated with the model.
   */
  componentsCount: number;
  /**
   * Number of relationships associated with the model.
   */
  relationshipsCount: number;
  created_at?: string;
  updated_at?: string;
}
/**
 * Meshery Connections are managed and unmanaged resources that either through discovery or manual entry are tracked by Meshery. Learn more at https://docs.meshery.io/concepts/logical/connections
 */
export interface HttpsSchemasMesheryIoComponentJson1 {
  /**
   * ID
   */
  id: string;
  /**
   * Connection Name
   */
  name: string;
  /**
   * Credential ID
   */
  credential_id?: string;
  /**
   * Connection Type
   */
  type: string;
  /**
   * Connection Subtype
   */
  sub_type: string;
  /**
   * Connection Kind
   */
  kind: string;
  metadata?: {
    [k: string]: unknown;
  };
  /**
   * Connection Status
   */
  status:
    | "discovered"
    | "registered"
    | "connected"
    | "ignored"
    | "maintenance"
    | "disconnected"
    | "deleted"
    | "not found";
  /**
   * A Universally Unique Identifier used to uniquely identify entites in Meshery. The UUID core defintion is used across different schemas.
   */
  user_id?: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
  environments?: HttpsSchemasMesheryIoEnvironmentJson[];
  /**
   * Specifies the version of the schema used for the definition.
   */
  schemaVersion: string;
}
/**
 * Meshery Environments allow you to logically group related Connections and their associated Credentials.. Learn more at https://docs.meshery.io/concepts/logical/environments
 */
export interface HttpsSchemasMesheryIoEnvironmentJson {
  /**
   * ID
   */
  id: string;
  /**
   * Environment name
   */
  name: string;
  /**
   * Environment description
   */
  description: string;
  /**
   * Environment organization ID
   */
  organization_id: string;
  /**
   * Environment owner
   */
  owner?: string;
  created_at?: string;
  metadata?: {
    [k: string]: unknown;
  };
  updated_at?: string;
  deleted_at?: string;
}
/**
 * Category of the model.
 */
export interface HttpsSchemasMesheryIoCategoryJson {
  /**
   * A Universally Unique Identifier used to uniquely identify entites in Meshery. The UUID core defintion is used across different schemas.
   */
  id: string;
  /**
   * The category of the model that determines the main grouping.
   */
  name:
    | "Analytics"
    | "App Definition and Development"
    | "Cloud Native Network"
    | "Cloud Native Storage"
    | "Database"
    | "Machine Learning"
    | "Observability and Analysis"
    | "Orchestration & Management"
    | "Platform"
    | "Provisioning"
    | "Runtime"
    | "Security & Compliance"
    | "Serverless"
    | "Tools"
    | "Uncategorized";
  metadata: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Meshery manages entities in accordance with their specific capabilities. This field explicitly identifies those capabilities largely by what actions a given component supports; e.g. metric-scrape, sub-interface, and so on. This field is extensible. Entities may define a broad array of capabilities, which are in-turn dynamically interpretted by Meshery for full lifecycle management.
 */
export interface HttpsSchemasMesheryIoCapabilityJson {
  /**
   * Specifies the version of the schema to which the capability definition conforms.
   */
  schemaVersion: string;
  /**
   * Version of the capability definition.
   */
  version: string;
  /**
   * Name of the capability in human-readible format.
   */
  displayName: string;
  /**
   * A written representation of the purpose and characteristics of the capability.
   */
  description: string;
  /**
   * Top-level categorization of the capability
   */
  kind: ("action" | "mutate" | "view" | "interaction") & string;
  /**
   * Classification of capabilities. Used to group capabilities similar in nature.
   */
  type: string;
  /**
   * Most granular unit of capability classification. The combination of Kind, Type and SubType together uniquely identify a Capability.
   */
  subType: string;
  /**
   * Key that backs the capability.
   */
  key: string;
  /**
   * State of the entity in which the capability is applicable.
   */
  entityState: ("declaration" | "instance")[];
  /**
   * Status of the capability
   */
  status: "enabled" | "disabled";
  /**
   * Metadata contains additional information associated with the capability. Extension point.
   */
  metadata?: {
    [k: string]: unknown;
  };
}
/**
 * Registrant-defined data associated with the model. Properties pertain to the software being managed (e.g. Kubernetes v1.31).
 */
export interface Model {
  /**
   * Version of the model as defined by the registrant.
   */
  version: string;
  [k: string]: unknown;
}
/**
 * Reference to the specific registered model to which the component belongs and from which model version, category, and other properties may be referenced. Learn more at https://docs.meshery.io/concepts/models
 */
export interface ModelReference {
  /**
   * A Universally Unique Identifier used to uniquely identify entites in Meshery. The UUID core defintion is used across different schemas.
   */
  id: string;
  /**
   * The unique name for the model within the scope of a registrant.
   */
  name: string;
  /**
   * Version of the model definition.
   */
  version: string;
  /**
   * Human-readable name for the model.
   */
  displayName: string;
  model: Model;
  registrant: RegistrantReference;
  [k: string]: unknown;
}
export interface RegistrantReference {
  kind: string;
  [k: string]: unknown;
}
/**
 * Common styles for all entities
 */
export interface Styles {
  /**
   * Primary color of the component used for UI representation.
   */
  primaryColor: string;
  /**
   * Secondary color of the entity used for UI representation.
   */
  secondaryColor?: string;
  /**
   * White SVG of the entity used for UI representation on dark background.
   */
  svgWhite: string;
  /**
   * Colored SVG of the entity used for UI representation on light background.
   */
  svgColor: string;
  /**
   * Complete SVG of the entity used for UI representation, often inclusive of background.
   */
  svgComplete: string;
  /**
   * The color of the element's label. Colours may be specified by name (e.g. red), hex (e.g.
   */
  color?: string;
  /**
   * The opacity of the label text, including its outline.
   */
  "text-opacity"?: number;
  /**
   * A comma-separated list of font names to use on the label text.
   */
  "font-family"?: string;
  /**
   * The size of the label text.
   */
  "font-size"?: string;
  /**
   * A CSS font style to be applied to the label text.
   */
  "font-style"?: string;
  /**
   * A CSS font weight to be applied to the label text.
   */
  "font-weight"?: string;
  /**
   * A transformation to apply to the label text
   */
  "text-transform"?: "none" | "uppercase" | "lowercase";
  /**
   * The opacity of the element, ranging from 0 to 1. Note that the opacity of a compound node parent affects the effective opacity of its children.
   */
  opacity?: number;
  /**
   * An integer value that affects the relative draw order of elements. In general, an element with a higher z-index will be drawn on top of an element with a lower z-index. Note that edges are under nodes despite z-index.
   */
  "z-index"?: number;
  /**
   * The text to display for an element's label. Can give a path, e.g. data(id) will label with the elements id
   */
  label?: string;
  /**
   * The animation to apply to the element. example ripple,bounce,etc
   */
  animation?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Meshery manages entities in accordance with their specific capabilities. This field explicitly identifies those capabilities largely by what actions a given component supports; e.g. metric-scrape, sub-interface, and so on. This field is extensible. Entities may define a broad array of capabilities, which are in-turn dynamically interpretted by Meshery for full lifecycle management.
 */
export interface HttpsSchemasMesheryIoCapabilityJson1 {
  /**
   * Specifies the version of the schema to which the capability definition conforms.
   */
  schemaVersion: string;
  /**
   * Version of the capability definition.
   */
  version: string;
  /**
   * Name of the capability in human-readible format.
   */
  displayName: string;
  /**
   * A written representation of the purpose and characteristics of the capability.
   */
  description: string;
  kind: ("action" | "mutate" | "view" | "interaction") & string;
  /**
   * Classification of capabilities. Used to group capabilities similar in nature.
   */
  type: string;
  /**
   * Most granular unit of capability classification. The combination of Kind, Type and SubType together uniquely identify a Capability.
   */
  subType: string;
  /**
   * Key that backs the capability.
   */
  key: string;
  /**
   * State of the entity in which the capability is applicable.
   */
  entityState: ("declaration" | "instance")[];
  /**
   * Status of the capability
   */
  status: "enabled" | "disabled";
  /**
   * Metadata contains additional information associated with the capability. Extension point.
   */
  metadata?: {
    [k: string]: unknown;
  };
}
/**
 * data related to the third party capability that Component Defintion wraps , this is herematicaly sealed an
 */
export interface Component {
  /**
   * Version of the component produced by the registrant. Example: APIVersion of a Kubernetes Pod.
   */
  version: string;
  /**
   * The unique identifier (name) assigned by the registrant to this component. Example: A Kubernetes Pod is of kind 'Pod'.
   */
  kind: string;
  /**
   * JSON schema of the object as defined by the registrant.
   */
  schema: string;
  [k: string]: unknown;
}
