openapi: 3.0.0
info:
  title: Keychain
  description: OpenAPI schema for keychain management in Meshery.
  version: v1beta1
  contact:
    name: Meshery Maintainers
    email: maintainers@meshery.io
    url: https://meshery.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

security:
  - jwt: []

tags:
  - name: Keychain
    description: Operations related to keychains

paths:
  /api/auth/keychains:
    $ref: "./keychain_operations.yml#/collection"
  /api/auth/keychains/{keychainId}:
    $ref: "./keychain_operations.yml#/item"
  /api/auth/keychains/{keychainId}/{keyId}:
    $ref: "./keychain_operations.yml#/itemKey"
  /api/auth/keychains/{keychainId}/keys:
    $ref: "./keychain_operations.yml#/itemKeys"

components:
  responses:
    400:
      $ref: "../core/api.yml#/components/responses/400"
    401:
      $ref: "../core/api.yml#/components/responses/401"
    404:
      $ref: "../core/api.yml#/components/responses/404"
    500:
      $ref: "../core/api.yml#/components/responses/500"

  parameters:
    keyId:
      name: keyId
      in: path
      description: Key ID
      required: true
      schema:
        $ref: ../core/api.yml#/components/schemas/uuid
    keychainId:
      name: keychainId
      in: path
      description: Keychain ID
      required: true
      schema:
        $ref: ../core/api.yml#/components/schemas/uuid
    page:
      $ref: ../core/api.yml#/components/parameters/page
    pagesize:
      $ref: ../core/api.yml#/components/parameters/pagesize
    order:
      $ref: ../core/api.yml#/components/parameters/order
    search:
      $ref: ../core/api.yml#/components/parameters/search

  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Keychain:
      $ref: "./keychain.yaml"
    KeychainInput:
      type: object
      description: Input payload for creating or updating a keychain.
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the keychain.
          x-order: 1
          minLength: 1
          maxLength: 255
        owner:
          $ref: "../core/api.yml#/components/schemas/uuid"
          description: Owner of the keychain.
          x-order: 2
    KeychainPage:
      type: object
      required:
        - page
        - page_size
        - total_count
        - keychains
      properties:
        page:
          $ref: ../core/api.yml#/components/schemas/number
          x-order: 1
        page_size:
          $ref: ../core/api.yml#/components/schemas/number
          x-order: 2
        total_count:
          $ref: ../core/api.yml#/components/schemas/number
          x-order: 3
        keychains:
          type: array
          items:
            $ref: "#/components/schemas/Keychain"
          x-order: 4
          description: The keychains of the keychainpage.
