package validation

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// oapi-codegen's version must come from exactly one place: the `tool` directive
// in go.mod. It previously came from four that disagreed - go.mod pinned
// v2.5.0, the Makefile and both publishing workflows installed v2.5.1, and
// build/generate-golang.js prepended $GOPATH/bin to PATH so the binary that
// actually ran was whichever one the contributor happened to have installed.
// The committed tree still carries the evidence: three models generated by
// v2.3.0 alongside the rest. See meshery/schemas#1194.

// repoRoot resolves the repository root, which is the parent of this package.
func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("..")
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	return root
}

// readRepoFile reads a repository-relative file, failing the test if it is missing.
func readRepoFile(t *testing.T, rel string) string {
	t.Helper()
	body, err := os.ReadFile(filepath.Join(repoRoot(t), rel))
	if err != nil {
		t.Fatalf("read %s: %v", rel, err)
	}
	return string(body)
}

// A pinned install of a second copy would put an unpinned binary on PATH and
// silently win over the module's own pin.
func TestNoHardcodedOapiCodegenVersionOutsideGoMod(t *testing.T) {
	// Any @ref, not just a numeric one: `@latest` and `@main` are worse than a
	// pinned version, not better.
	install := regexp.MustCompile(`go\s+install\s+\S*oapi-codegen/v2/cmd/oapi-codegen@\S+`)

	var scanned int
	walk := func(rel string) {
		root := filepath.Join(repoRoot(t), rel)
		err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return err
			}
			body, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			scanned++
			if install.Match(body) {
				short, _ := filepath.Rel(repoRoot(t), path)
				t.Errorf("%s installs oapi-codegen standalone; the `tool` directive in go.mod is the only pin", short)
			}
			return nil
		})
		if err != nil {
			t.Fatalf("walk %s: %v", rel, err)
		}
	}
	walk(".github/workflows")
	walk("build")

	if install.MatchString(readRepoFile(t, "Makefile")) {
		t.Error("Makefile installs oapi-codegen standalone; the `tool` directive in go.mod is the only pin")
	}
	if scanned == 0 {
		t.Fatal("scanned no files; the guard would pass vacuously")
	}
}

func TestGoModDeclaresTheOapiCodegenTool(t *testing.T) {
	gomod := readRepoFile(t, "go.mod")
	if !strings.Contains(gomod, "tool github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen") {
		t.Error("go.mod is missing the oapi-codegen `tool` directive that pins the generator")
	}
}

// The generator must resolve the tool through the module, and must not put
// $GOPATH/bin ahead of it - that override is what made the effective version
// "whatever is installed" no matter what any pin said.
func TestGeneratorUsesThePinnedTool(t *testing.T) {
	script := readRepoFile(t, "build/generate-golang.js")

	if !strings.Contains(script, "go tool oapi-codegen --config") {
		t.Error("build/generate-golang.js must invoke `go tool oapi-codegen` so go.mod decides the version")
	}
	if regexp.MustCompile(`process\.env\.PATH\s*=`).MatchString(script) {
		t.Error("build/generate-golang.js must not rewrite PATH; that is how an unpinned binary won before")
	}
}
