openapi: 3.0.0
info:
  title: Meshery Server
  description: Documentation for Meshery Server REST APIs.
  version: v0.8.0
  contact:
    name: Meshery Maintainers
    email: maintainers@meshery.io
    url: https://meshery.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://playground.meshery.io
    description: Meshery Playground server URL
  - url: https://staging-cloud.meshery.io
    description: Meshery Cloud staging server URL
  - url: http://localhost:9081
    description: >
      Meshery Server development server URL (controlled via PORT environment
      variable)
