openapi: 3.0.0
info:
  title: Meshery Cloud
  description: Documentation for meshery Cloud REST APIs
  contact:
    email: support@layer5.io
  version: v0.6.394
servers:
  - url: https://meshery.layer5.io
    description: Meshery Cloud production server URL
  - url: https://staging-meshery.layer5.io
    description: Meshery Cloud staging server URL
  - url: http://localhost:9876
    description: Meshery Cloud development server URL (controlled via PORT environment variable)
tags:
  - name: user_onboarding
    description: APIs for user onboarding
security: 
  -  jwt: []

components:
  securitySchemes:
    jwt:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  
  schemas: 
    signupData:
      properties:
        id:
          $ref: './common/core.yml#/id'
        first_name:
          $ref: './common/core.yml#/text'
          description: First Name
        last_name:
          $ref: './common/core.yml#/text'
          description: Last Name
        email:
          $ref: './common/core.yml#/email'
        occupation:
          $ref: './common/core.yml#/text'
          description: Occupation
        organization:
          $ref: './common/core.yml#/text'
          description: Organization
        role:
          $ref: './common/core.yml#/text'
          description: Role in organization
        form_type:
          $ref: './common/core.yml#/text'
          description: Form Type (MeshMap or Playground)
        status:
          $ref: './common/core.yml#/text'
          description: Status (approved / denied)
        task_id:
          $ref: './common/core.yml#/text'
          description: ClickUp task id
        task_link:
          $ref: './common/core.yml#/text'
          description: ClickUp task link
        created_at:
          $ref: './common/core.yml#/time'
        updated_at:
          $ref: './common/core.yml#/time'

    signupRequestsPage:
      allOf:
      - $ref: './common/core.yml#/resultsPage'
      - type: object
        properties:
          signup_data:
            type: array
            items:
              $ref: '#/components/schemas/signupData'
  
  requestBodies:  
    signupData:
      description: Body for updating user signup request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/signupData'
paths:
  /api/identity/users/request:
      post:
        tags:
          - user onboarding
        operationId: SignupRequest
        summary: Sign up request
        description: Updates user singup request
        requestBody:
          $ref: '#/components/requestBodies/signupData'
        responses:
          '200':
            $ref: './common/responses.yml#/200'
          '401':
            $ref: './common/responses.yml#/401'
          '500':
            $ref: './common/responses.yml#/500'
      get:
        tags:
          - user onboarding
        operationId: GetSignupRequests
        summary: Get all Signup requests
        description: Get all Signup requests
        parameters:
          - $ref: './common/parameters.yml#/page'
          - $ref: './common/parameters.yml#/page_size'
          - $ref: './common/parameters.yml#/search'
          - $ref: './common/parameters.yml#/order'
          - $ref: './common/parameters.yml#/requestFilter'
        responses:
          '200':
            description: Signup request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/signupRequestsPage'
          '401':
            $ref: './common/responses.yml#/401'
          '500':
            $ref: './common/responses.yml#/500'
  /api/identity/users/request/approve:
    post:
      tags:
        - user onboarding
      operationId: ApproveSignupRequest
      summary: Approve Signup request
      description: Approve Signup request
      parameters:
        - name: id
          in: query
          description: Signup request id
          schema:
            $ref: ./common/core.yml#/id
        - name: first_name
          in: query
          description: First Name
          schema:
            type: string
        - name: last_name
          in: query
          description: Last Name
          schema:
            type: string
        - name: occupation
          in: query
          description: Email
          schema:
            $ref: ./common/core.yml#/email
        - name: organization
          in: query
          description: Organization
          schema:
            type: string
        - name: role
          in: query
          description: Role in organization
          schema:
            type: string
        - name: form_type
          in: query
          description: Form Type (MeshMap or Playground)
          schema:
            type: string
        - name: status
          in: query
          description: Status (approved / denied)
          schema:
            type: string
        - name: task_id
          in: query
          description: Click up task id
          schema:
            type: string
        - name: task_link
          in: query
          description: Click up task link
          schema:
            type: string
      responses:
        '200':
          $ref: './common/responses.yml#/200'
        '400':
          $ref: './common/responses.yml#/400'
        '401':
          $ref: './common/responses.yml#/401'
        '500':
          $ref: './common/responses.yml#/500'
  /api/identity/users/request/deny:
    post:
      tags:
        - user onboarding
      operationId: DenySignupRequest
      summary: Deny signup request
      description: Deny Signup Request
      parameters:
        - name: id
          in: query
          description: Signup request id
          schema:
            $ref: ./common/core.yml#/id
        - name: first_name
          in: query
          description: First Name
          schema:
            type: string
        - name: last_name
          in: query
          description: Last Name
          schema:
            type: string
        - name: occupation
          in: query
          description: Email
          schema:
            $ref: ./common/core.yml#/email
        - name: organization
          in: query
          description: Organization
          schema:
            type: string
        - name: role
          in: query
          description: Role in organization
          schema:
            type: string
        - name: form_type
          in: query
          description: Form Type (MeshMap or Playground)
          schema:
            type: string
        - name: status
          in: query
          description: Status (approved / denied)
          schema:
            type: string
        - name: task_id
          in: query
          description: Click up task id
          schema:
            type: string
        - name: task_link
          in: query
          description: Click up task link
          schema:
            type: string
      responses:
        '200':
          $ref: './common/responses.yml#/200'
        '400':
          $ref: './common/responses.yml#/400'
        '401':
          $ref: './common/responses.yml#/401'
        '500':
          $ref: './common/responses.yml#/500'
  /api/identity/users/request/approve/{id}:
    get:
      tags:
        - user onboarding
      operationId: ApproveSignupRequestByID
      summary: Approve signup request by ID
      description: Approve signup request associated with ID
      parameters:
        - $ref: './common/parameters.yml#/id'
      responses:
        '302':
          description: 'Redirect: SERVER_BASE_URL/profile/roles'
        '303':
          description: 'Redirect: SERVER_BASE_URL/?source=<base64 encoded source url>'
        '400':
          $ref: './common/responses.yml#/400'
        '401':
          $ref: './common/responses.yml#/401'
        '500':
          $ref: './common/responses.yml#/500'
  /api/identity/users/request/deny/{id}:
    get:
      tags:
        - user onboarding
      operationId: DenySignupRequestByID
      summary: Deny signup request by ID
      description: Deny signup request associated with ID
      parameters:
        - $ref: './common/parameters.yml#/id'
      responses:
        '302':
          description: 'Redirect: SERVER_BASE_URL/profile/roles'
        '303':
          description: 'Redirect: SERVER_BASE_URL/?source=<base64 encoded source url>'
        '400':
          $ref: './common/responses.yml#/400'
        '401':
          $ref: './common/responses.yml#/401'
        '500':
          $ref: './common/responses.yml#/500'
  /api/identity/users/request/notification:
    get:
      tags:
        - user onboarding
      operationId: GetSignupRequestNotification
      summary: Signup request notification
      description: Signup request notification
      responses:
        '200':
          description: Signup request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signupData'
        '204':
          description: Status no content
        '401':
          $ref: './common/responses.yml#/401'