// Package performance_profile provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package performance_profile

import (
	"github.com/lib/pq"
	"github.com/meshery/schemas/models/core"
)

// PerformanceProfile A performance profile captures the configuration for a load test run by Meshery against one or more service-mesh endpoints. Profiles are owned by a user and can optionally be associated with a recurring schedule. Learn more at https://docs.meshery.io/tasks/performance-management
type PerformanceProfile struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID core.Uuid `db:"id" json:"id" yaml:"id"`

	// Name Human-readable name of the performance profile.
	Name string `db:"name" json:"name" yaml:"name"`

	// UserId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	UserID core.Uuid `db:"user_id" json:"userId" yaml:"userId"`

	// Schedule A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Schedule *core.Uuid `db:"schedule" json:"schedule,omitempty" yaml:"schedule,omitempty"`

	// LoadGenerators Load generators (e.g. fortio, wrk2, nighthawk) to drive the profile's load test.
	LoadGenerators pq.StringArray `db:"load_generators" json:"loadGenerators" yaml:"loadGenerators"`

	// Endpoints Endpoints (URLs) targeted by the performance profile's load test.
	Endpoints pq.StringArray `db:"endpoints" json:"endpoints" yaml:"endpoints"`

	// ServiceMesh Service mesh under test for the profile (e.g. istio, linkerd, consul). Empty string when the profile is mesh-agnostic.
	ServiceMesh string `db:"service_mesh" json:"serviceMesh" yaml:"serviceMesh"`

	// ConcurrentRequest Number of concurrent requests issued by the load generator.
	ConcurrentRequest int `db:"concurrent_request" json:"concurrentRequest" yaml:"concurrentRequest"`

	// QPS Target queries-per-second rate for the load generator. Zero indicates the generator runs unthrottled.
	QPS int `db:"qps" json:"qps" yaml:"qps"`

	// Duration Duration of the load test, expressed as a Go duration string (e.g. "30s", "5m", "1h").
	Duration string `db:"duration" json:"duration" yaml:"duration"`

	// RequestHeaders HTTP request headers, serialized as JSON, sent on each load-test request. Empty string when no headers are configured.
	RequestHeaders string `db:"request_headers" json:"requestHeaders" yaml:"requestHeaders"`

	// RequestCookies HTTP request cookies, serialized as JSON, sent on each load-test request. Empty string when no cookies are configured.
	RequestCookies string `db:"request_cookies" json:"requestCookies" yaml:"requestCookies"`

	// RequestBody HTTP request body sent on each load-test request. Empty string when no body is configured.
	RequestBody string `db:"request_body" json:"requestBody" yaml:"requestBody"`

	// ContentType Content-Type header value applied to each load-test request body (e.g. "application/json"). Empty string when no body is configured.
	ContentType string `db:"content_type" json:"contentType" yaml:"contentType"`

	// Metadata Free-form metadata associated with the performance profile.
	Metadata core.Map `db:"metadata" json:"metadata" yaml:"metadata"`

	// LastRun SQL null Timestamp to handle null values of time.
	LastRun core.NullTime `db:"last_run" json:"lastRun,omitempty" yaml:"lastRun,omitempty"`

	// TotalResults Server-computed count of load-test results recorded for this profile. Server-managed; clients must not set this on create/update.
	TotalResults int `db:"total_results" json:"totalResults" yaml:"totalResults"`

	// CreatedAt Timestamp when the resource was created.
	CreatedAt core.CreatedAt `db:"created_at" json:"createdAt" yaml:"createdAt"`

	// UpdatedAt Timestamp when the resource was updated.
	UpdatedAt core.UpdatedAt `db:"updated_at" json:"updatedAt" yaml:"updatedAt"`
}

// PerformanceProfilePage Paginated list of performance profiles.
type PerformanceProfilePage struct {
	// Page Zero-based page index returned in this response.
	Page int `json:"page" yaml:"page"`

	// PageSize Maximum number of items returned on each page.
	PageSize int `json:"pageSize" yaml:"pageSize"`

	// Profiles Performance profiles in this page.
	Profiles []PerformanceProfile `json:"profiles" yaml:"profiles"`

	// TotalCount Total number of performance profiles across all pages.
	TotalCount int `json:"totalCount" yaml:"totalCount"`
}

// PerformanceProfilePayload Payload for creating or updating a performance profile. Includes only client-settable fields; server-generated fields (id on create, createdAt, updatedAt, lastRun, totalResults) are populated by the server.
type PerformanceProfilePayload struct {
	// ConcurrentRequest Number of concurrent requests issued by the load generator.
	ConcurrentRequest int `json:"concurrentRequest,omitempty" yaml:"concurrentRequest,omitempty"`

	// ContentType Content-Type header value applied to each load-test request body (e.g. "application/json").
	ContentType string `json:"contentType,omitempty" yaml:"contentType,omitempty"`

	// Duration Duration of the load test, expressed as a Go duration string (e.g. "30s", "5m", "1h").
	Duration string `json:"duration" yaml:"duration"`

	// Endpoints Endpoints (URLs) targeted by the performance profile's load test.
	Endpoints pq.StringArray `json:"endpoints" yaml:"endpoints"`

	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID *core.Uuid `json:"id,omitempty" yaml:"id,omitempty"`

	// LoadGenerators Load generators (e.g. fortio, wrk2, nighthawk) to drive the profile's load test.
	LoadGenerators pq.StringArray `json:"loadGenerators" yaml:"loadGenerators"`

	// Metadata Free-form metadata associated with the performance profile.
	Metadata core.Map `json:"metadata,omitempty" yaml:"metadata,omitempty"`

	// Name Human-readable name of the performance profile.
	Name string `json:"name" yaml:"name"`

	// QPS Target queries-per-second rate for the load generator. Zero indicates the generator runs unthrottled.
	QPS int `json:"qps,omitempty" yaml:"qps,omitempty"`

	// RequestBody HTTP request body sent on each load-test request.
	RequestBody string `json:"requestBody,omitempty" yaml:"requestBody,omitempty"`

	// RequestCookies HTTP request cookies, serialized as JSON, sent on each load-test request.
	RequestCookies string `json:"requestCookies,omitempty" yaml:"requestCookies,omitempty"`

	// RequestHeaders HTTP request headers, serialized as JSON, sent on each load-test request.
	RequestHeaders string `json:"requestHeaders,omitempty" yaml:"requestHeaders,omitempty"`

	// Schedule A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Schedule *core.Uuid `json:"schedule,omitempty" yaml:"schedule,omitempty"`

	// ServiceMesh Service mesh under test for the profile (e.g. istio, linkerd, consul). Empty string when the profile is mesh-agnostic.
	ServiceMesh string `json:"serviceMesh,omitempty" yaml:"serviceMesh,omitempty"`

	// UserId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	UserID *core.Uuid `json:"userId,omitempty" yaml:"userId,omitempty"`
}

// Order defines model for order.
type Order = string

// Page defines model for page.
type Page = string

// Pagesize defines model for pagesize.
type Pagesize = string

// PerformanceProfileId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type PerformanceProfileId = core.Uuid

// Search defines model for search.
type Search = string
