// This is not autogenerated.
package environment

import (
	"encoding/json"
	"testing"
)

// TestIsAdministrativeFailsClosed pins the direction the predicate errs in.
// Every value that is not exactly the administrative literal - including the
// zero value that rows predating the column read back as, and any purpose a
// later schema version adds - must answer false. A regression here silently
// promotes ordinary environments to the trusted ones.
func TestIsAdministrativeFailsClosed(t *testing.T) {
	cases := []struct {
		name    string
		purpose EnvironmentPurpose
		want    bool
	}{
		{"administrative", EnvironmentPurposeAdministrative, true},
		{"user", EnvironmentPurposeUser, false},
		{"absent (pre-migration row)", "", false},
		{"unrecognised future value", EnvironmentPurpose("billing"), false},
		{"casing variant", EnvironmentPurpose("Administrative"), false},
		{"whitespace padded", EnvironmentPurpose(" administrative"), false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := (Environment{Purpose: tc.purpose}).IsAdministrative(); got != tc.want {
				t.Fatalf("IsAdministrative() with purpose %q = %v, want %v", tc.purpose, got, tc.want)
			}
		})
	}
}

// TestEffectivePurposeResolvesAbsentToUser covers the documented equivalence
// of an absent purpose and the explicit user purpose.
func TestEffectivePurposeResolvesAbsentToUser(t *testing.T) {
	if got := (Environment{}).EffectivePurpose(); got != EnvironmentPurposeUser {
		t.Fatalf("EffectivePurpose() on a zero Environment = %q, want %q", got, EnvironmentPurposeUser)
	}
	if got := (Environment{Purpose: EnvironmentPurposeAdministrative}).EffectivePurpose(); got != EnvironmentPurposeAdministrative {
		t.Fatalf("EffectivePurpose() = %q, want %q", got, EnvironmentPurposeAdministrative)
	}
}

// TestEnvironmentPayloadCannotCarryPurpose is the schema half of the guarantee
// that permission to create an environment does not confer permission to make
// one administrative: EnvironmentPayload has no field the property can decode
// into, so a request that supplies one is dropped rather than honoured.
//
// This is a codegen guarantee, not access control. Every consumer must also
// refuse to set Purpose from request input on its own side - a consumer that
// copies an entity struct straight out of a request body bypasses this
// entirely. The test exists so that adding Purpose to the payload schema,
// which would remove the guarantee, cannot pass unnoticed. It is the only
// mechanism in the schema, because the readOnly annotation that would normally
// accompany it corrupts the generated RTK client - see
// docs/environment-purpose-contract.md.
func TestEnvironmentPayloadCannotCarryPurpose(t *testing.T) {
	var payload EnvironmentPayload
	body := []byte(`{"name":"attacker","organizationId":"00000000-0000-0000-0000-000000000000","purpose":"administrative"}`)
	if err := json.Unmarshal(body, &payload); err != nil {
		t.Fatalf("unmarshal payload: %v", err)
	}

	round, err := json.Marshal(payload)
	if err != nil {
		t.Fatalf("marshal payload: %v", err)
	}
	var got map[string]any
	if err := json.Unmarshal(round, &got); err != nil {
		t.Fatalf("unmarshal round-tripped payload: %v", err)
	}
	if _, present := got["purpose"]; present {
		t.Fatal("EnvironmentPayload round-tripped a purpose field; the payload schema must not expose purpose - see schemas/constructs/v1beta3/environment/api.yml")
	}
}

// TestPurposeIsOmittedWhenAbsent guards the wire contract for the unset value.
// EnvironmentPurpose is a bare string, so without omitempty an unset purpose
// would serialise as "" - a value the enum does not admit, which would make
// every response for a pre-migration row fail validation against the schema
// this repo publishes.
func TestPurposeIsOmittedWhenAbsent(t *testing.T) {
	encoded, err := json.Marshal(Environment{})
	if err != nil {
		t.Fatalf("marshal environment: %v", err)
	}
	var got map[string]any
	if err := json.Unmarshal(encoded, &got); err != nil {
		t.Fatalf("unmarshal environment: %v", err)
	}
	if _, present := got["purpose"]; present {
		t.Fatalf("an unset purpose must be omitted from the wire, got %s", encoded)
	}

	encoded, err = json.Marshal(Environment{Purpose: EnvironmentPurposeAdministrative})
	if err != nil {
		t.Fatalf("marshal environment: %v", err)
	}
	if err := json.Unmarshal(encoded, &got); err != nil {
		t.Fatalf("unmarshal environment: %v", err)
	}
	if got["purpose"] != string(EnvironmentPurposeAdministrative) {
		t.Fatalf("purpose = %v, want %q", got["purpose"], EnvironmentPurposeAdministrative)
	}
}
