/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a page of connections with a meta information about connections number
 */
export interface HttpsSchemasMesheryIoComponentJson {
  connections: HttpsSchemasMesheryIoComponentJson1[];
  /**
   * Total number of connections on all pages
   */
  total_count: number;
  /**
   * Page number
   */
  page: number;
  /**
   * Number of elements per page
   */
  page_size: number;
}
/**
 * List of connections on this page
 */
export interface HttpsSchemasMesheryIoComponentJson1 {
  /**
   * ID
   */
  id: string;
  /**
   * Connection Name
   */
  name: string;
  /**
   * Credential ID
   */
  credential_id?: string;
  /**
   * Connection Type
   */
  type: string;
  /**
   * Connection Subtype
   */
  sub_type: string;
  /**
   * Connection Kind
   */
  kind: string;
  metadata?: {
    [k: string]: unknown;
  };
  /**
   * Connection Status
   */
  status:
    | "discovered"
    | "registered"
    | "connected"
    | "ignored"
    | "maintenance"
    | "disconnected"
    | "deleted"
    | "not found";
  /**
   * A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
   */
  user_id?: string;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string;
  environments?: HttpsSchemasMesheryIoEnvironmentJson[];
  /**
   * Specifies the version of the schema used for the definition.
   */
  schemaVersion: string;
}
/**
 * Meshery Environments allow you to logically group related Connections and their associated Credentials.. Learn more at https://docs.meshery.io/concepts/logical/environments
 */
export interface HttpsSchemasMesheryIoEnvironmentJson {
  /**
   * ID
   */
  id: string;
  /**
   * Environment name
   */
  name: string;
  /**
   * Environment description
   */
  description: string;
  /**
   * Environment organization ID
   */
  organization_id: string;
  /**
   * Environment owner
   */
  owner?: string;
  created_at?: string;
  metadata?: {
    [k: string]: unknown;
  };
  updated_at?: string;
  deleted_at?: string;
}
